const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.ScriptsInEvents.EventSheet1_Event77_Act4,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{row: 0},
	{id: 0},
	{type: 0},
	{hasHint: 0},
	{Tween: 0},
	{SlotInput: 0},
	{Browser: 0},
	{parent: 0},
	{hint: 0},
	{SlotInputText: 0},
	{Letter: 0},
	{Parent: 0},
	{KeyboardInput: 0},
	{Translation: 0},
	{KeyboardInputText: 0},
	{Touch: 0},
	{MoveTo: 0},
	{FloatingText: 0},
	{Sine: 0},
	{retry: 0},
	{TiledBackground: 0},
	{Gamemanager: 0},
	{TutorialText: 0},
	{EndscreenTitleText: 0},
	{ReplayButton: 0},
	{ReplayButtonText: 0},
	{EndscreenText: 0},
	{TutorialTitleText: 0},
	{SettingLanguageIcon: 0},
	{TutorialButton: 0},
	{SettingButton: 0},
	{CloseButton: 0},
	{SettingTitleText: 0},
	{SettingLanguageTitleText: 0},
	{InfoText: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{LevelText: 0},
	{RuleText: 0},
	{DifficultyTitleText: 0},
	{word: 0},
	{DifficultyButton: 0},
	{DifficultyButtonText: 0},
	{HintButton: 0},
	{HintButtonText: 0},
	{GameMonetizeSDK: 0},
	{Buttons: 0},
	{currentRow: 0},
	{currentID: 0},
	{isEnabled: 0},
	{language: 0},
	{newGame: 0},
	{WordLength: 0},
	{HintAmount: 0},
	{HintSlots: 0},
	{loop: 0},
	{ID: 0},
	{Row: 0},
	{final_word: 0},
	{number: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	SlotInput: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	SlotInputText: class extends self.ITextInstance {},
	KeyboardInput: class extends self.ISpriteInstance {},
	KeyboardInputText: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	FloatingText: class extends self.ITextInstance {},
	retry: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Gamemanager: class extends self.ISpriteInstance {},
	TutorialText: class extends self.ITextInstance {},
	EndscreenTitleText: class extends self.ITextInstance {},
	ReplayButton: class extends self.ISpriteInstance {},
	ReplayButtonText: class extends self.ITextInstance {},
	EndscreenText: class extends self.ITextInstance {},
	TutorialTitleText: class extends self.ITextInstance {},
	SettingLanguageIcon: class extends self.ISpriteInstance {},
	TutorialButton: class extends self.ISpriteInstance {},
	SettingButton: class extends self.ISpriteInstance {},
	CloseButton: class extends self.ISpriteInstance {},
	SettingTitleText: class extends self.ITextInstance {},
	SettingLanguageTitleText: class extends self.ITextInstance {},
	InfoText: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	LevelText: class extends self.ITextInstance {},
	RuleText: class extends self.ITextInstance {},
	DifficultyTitleText: class extends self.ITextInstance {},
	DifficultyButton: class extends self.ISpriteInstance {},
	DifficultyButtonText: class extends self.ITextInstance {},
	HintButton: class extends self.ISpriteInstance {},
	HintButtonText: class extends self.ITextInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Buttons: class extends self.ISpriteInstance {}
}