const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Behaviors.Timer,
		C3.Plugins.Text,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.sliderbar,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.SpeechSynthesis,
		C3.Behaviors.Pin,
		C3.Plugins.video,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Function,
		C3.Plugins.GM_SDK,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.SpeechSynthesis.Acts.SpeakText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.SpeechSynthesis.Exps.VoiceLangAt,
		C3.Plugins.SpeechSynthesis.Exps.VoiceURIAt,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.SpeechSynthesis.Cnds.OnSpeechEnded,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.SpeechSynthesis.Acts.StopSpeaking,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetMeshSize,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Exps.MeshColumns,
		C3.Plugins.Sprite.Exps.MeshRows,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.SetLayoutScale
	];
};
self.C3_JsPropNameTable = [
	{VectorX: 0},
	{VectorY: 0},
	{RotationSpeed: 0},
	{Object: 0},
	{Background: 0},
	{Touch: 0},
	{Tween: 0},
	{Blade: 0},
	{Luminosity: 0},
	{HalfObject: 0},
	{Timer: 0},
	{JuiceParticles: 0},
	{BladeSmoother: 0},
	{InstructionsText: 0},
	{ScrollTo: 0},
	{GameManager: 0},
	{Flash: 0},
	{ScoreText: 0},
	{SmokeParticle: 0},
	{Fade: 0},
	{FireParticles: 0},
	{DrawingCanvas: 0},
	{SliceText: 0},
	{pozadina: 0},
	{Sine: 0},
	{dalje2: 0},
	{moregames: 0},
	{Loginy8: 0},
	{playerName: 0},
	{Loginy8moja: 0},
	{y8: 0},
	{openProfile: 0},
	{Sprite8: 0},
	{logo: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Audio: 0},
	{Browser: 0},
	{BSound: 0},
	{menu: 0},
	{charlimiruje: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{oci: 0},
	{ustadodir: 0},
	{klijestazaljepka: 0},
	{HalfObject2: 0},
	{HalfObject3: 0},
	{bibberdugme: 0},
	{cekicdugme: 0},
	{dinamit: 0},
	{klijesta: 0},
	{noz: 0},
	{Sprite: 0},
	{Sprite4: 0},
	{meshnagrada: 0},
	{sos: 0},
	{vatra: 0},
	{zub: 0},
	{busilica: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite9: 0},
	{zaslon: 0},
	{highscore: 0},
	{Score2: 0},
	{Score: 0},
	{LocalStorage: 0},
	{Sprite12: 0},
	{infotext: 0},
	{info: 0},
	{infozatvori: 0},
	{Index: 0},
	{PreviousX: 0},
	{PreviousY: 0},
	{CupShadow: 0},
	{Ball: 0},
	{HasTheBall: 0},
	{Cup: 0},
	{ID: 0},
	{DefaultY: 0},
	{IsShadow: 0},
	{Text: 0},
	{Blast: 0},
	{AdvancedRandom: 0},
	{Scoree: 0},
	{highscoree: 0},
	{Sprite13: 0},
	{Speed: 0},
	{Volume: 0},
	{Pitch: 0},
	{rijeci: 0},
	{Typebox: 0},
	{Stop: 0},
	{Speak: 0},
	{Box: 0},
	{VoiceNumber: 0},
	{Voice: 0},
	{Mouse: 0},
	{LanguageNumber: 0},
	{Language: 0},
	{Box2: 0},
	{SpeechSynthesis: 0},
	{SpeedText: 0},
	{VolumeText: 0},
	{PitchText: 0},
	{PlayZvuk: 0},
	{StopZvuk: 0},
	{TextInput: 0},
	{videozapatku: 0},
	{usta: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{pozadina2: 0},
	{tryagain: 0},
	{konfete: 0},
	{welldone: 0},
	{Pin: 0},
	{glava: 0},
	{Video: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{leaderboard: 0},
	{EnterNameBox: 0},
	{LimitReachedTXT: 0},
	{MeshColumn: 0},
	{MeshRow: 0},
	{DragDrop: 0},
	{MeshPoint: 0},
	{Piggy: 0},
	{Sprite18: 0},
	{hidedots: 0},
	{TakeScreenshotButton: 0},
	{BACK: 0},
	{Sprite19: 0},
	{ruka: 0},
	{HOME3: 0},
	{rep: 0},
	{Line: 0},
	{Sprite5: 0},
	{Sprite20: 0},
	{snijegplay: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{ToolTip: 0},
	{Snow: 0},
	{sonicdance2: 0},
	{Sprite23: 0},
	{pozadina3: 0},
	{Sprite24: 0},
	{grana: 0},
	{slice: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite2222: 0},
	{slike: 0},
	{Touchpoint: 0},
	{Brush_Color: 0},
	{Pencil: 0},
	{Frame: 0},
	{Show_Brush_Size: 0},
	{more2: 0},
	{btn_camera: 0},
	{Function: 0},
	{zoomin: 0},
	{zoomout: 0},
	{restart: 0},
	{crtanje: 0},
	{Sprite27: 0},
	{druga: 0},
	{treca: 0},
	{prva: 0},
	{cetvrta: 0},
	{slice2: 0},
	{slike2: 0},
	{GameMonetizeSDK: 0},
	{Highscore: 0},
	{PiggyLeft: 0},
	{PiggyTop: 0},
	{PiggyRight: 0},
	{PiggyBottom: 0},
	{FirstInteraction: 0},
	{DOUBLESPAWNRATE: 0},
	{BOMBSPAWNRATE: 0},
	{SCREENHORIZONTALMARGIN: 0},
	{RotationDirection: 0},
	{AllowPlayerToCut: 0},
	{RandomForce: 0},
	{GameIsOver: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{TotalMoves: 0},
	{RemainingMoves: 0},
	{Highscoree: 0},
	{NormalizedDifficulty: 0},
	{ROUNDSUNTILMAXDIFFICULTY: 0},
	{EASYDIVIDER: 0},
	{HARDDIVIDER: 0},
	{Sound: 0},
	{SoundEf: 0},
	{SelectedVoice: 0},
	{SelectedLanguage: 0},
	{AllowPlayerInput: 0},
	{IsFirstInteraction: 0},
	{SHADOWPROJECTIONANGLE: 0},
	{rekord: 0},
	{SHADOWPROJECTIONDISTANCE: 0},
	{CheckCupByIndex: 0},
	{FirstCupX: 0},
	{SecondCupX: 0},
	{DistanceBetweenCups: 0},
	{CupIndex: 0},
	{TextID: 0},
	{PenUID: 0},
	{Menu_layers: 0},
	{y_position: 0},
	{x_position: 0},
	{Set_Color_Frame: 0},
	{Brush_Size: 0},
	{Canvas_Image_Frame: 0}
];

self.InstanceType = {
	Object: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Blade: class extends self.ISpriteInstance {},
	HalfObject: class extends self.ISpriteInstance {},
	JuiceParticles: class extends self.IParticlesInstance {},
	BladeSmoother: class extends self.ISpriteInstance {},
	InstructionsText: class extends self.ITextInstance {},
	GameManager: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	SmokeParticle: class extends self.IParticlesInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	FireParticles: class extends self.IParticlesInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	SliceText: class extends self.ITextInstance {},
	pozadina: class extends self.ISpriteInstance {},
	dalje2: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	Loginy8: class extends self.IButtonInstance {},
	playerName: class extends self.ITextInstance {},
	Loginy8moja: class extends self.ISpriteInstance {},
	y8: class extends self.ISpriteInstance {},
	openProfile: class extends self.IButtonInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BSound: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	charlimiruje: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	oci: class extends self.ISpriteInstance {},
	ustadodir: class extends self.ISpriteInstance {},
	klijestazaljepka: class extends self.ISpriteInstance {},
	HalfObject2: class extends self.ISpriteInstance {},
	HalfObject3: class extends self.ISpriteInstance {},
	bibberdugme: class extends self.ISpriteInstance {},
	cekicdugme: class extends self.ISpriteInstance {},
	dinamit: class extends self.ISpriteInstance {},
	klijesta: class extends self.ISpriteInstance {},
	noz: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	meshnagrada: class extends self.ISpriteInstance {},
	sos: class extends self.ISpriteInstance {},
	vatra: class extends self.ISpriteInstance {},
	zub: class extends self.ISpriteInstance {},
	busilica: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	zaslon: class extends self.ISpriteInstance {},
	highscore: class extends self.ITextInstance {},
	Score2: class extends self.ITextInstance {},
	Score: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	infotext: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	infozatvori: class extends self.ISpriteInstance {},
	CupShadow: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Cup: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Blast: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Scoree: class extends self.ITextInstance {},
	highscoree: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Speed: class extends self.ISliderBarInstance {},
	Volume: class extends self.ISliderBarInstance {},
	Pitch: class extends self.ISliderBarInstance {},
	Typebox: class extends self.ITextInputInstance {},
	Stop: class extends self.IButtonInstance {},
	Speak: class extends self.IButtonInstance {},
	Box: class extends self.ISpriteInstance {},
	Voice: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Language: class extends self.ITextInstance {},
	Box2: class extends self.ISpriteInstance {},
	SpeechSynthesis: class extends self.IInstance {},
	SpeedText: class extends self.ITextInstance {},
	VolumeText: class extends self.ITextInstance {},
	PitchText: class extends self.ITextInstance {},
	PlayZvuk: class extends self.ISpriteInstance {},
	StopZvuk: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	videozapatku: class extends self.ISpriteInstance {},
	usta: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	pozadina2: class extends self.ISpriteInstance {},
	tryagain: class extends self.ISpriteInstance {},
	konfete: class extends self.ISpriteInstance {},
	welldone: class extends self.ISpriteInstance {},
	glava: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	leaderboard: class extends self.ISpriteInstance {},
	EnterNameBox: class extends self.ITextInputInstance {},
	LimitReachedTXT: class extends self.ITextInstance {},
	MeshPoint: class extends self.ISpriteInstance {},
	Piggy: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	hidedots: class extends self.ISpriteInstance {},
	TakeScreenshotButton: class extends self.IButtonInstance {},
	BACK: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	ruka: class extends self.ISpriteInstance {},
	HOME3: class extends self.ISpriteInstance {},
	rep: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	snijegplay: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Snow: class extends self.IParticlesInstance {},
	sonicdance2: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	pozadina3: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	grana: class extends self.ISpriteInstance {},
	slice: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite2222: class extends self.ISpriteInstance {},
	slike: class extends self.ISpriteInstance {},
	Touchpoint: class extends self.ISpriteInstance {},
	Brush_Color: class extends self.ISpriteInstance {},
	Pencil: class extends self.ISpriteInstance {},
	Show_Brush_Size: class extends self.ISpriteInstance {},
	more2: class extends self.ISpriteInstance {},
	btn_camera: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	zoomin: class extends self.ISpriteInstance {},
	zoomout: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	crtanje: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	druga: class extends self.ISpriteInstance {},
	treca: class extends self.ISpriteInstance {},
	prva: class extends self.ISpriteInstance {},
	cetvrta: class extends self.ISpriteInstance {},
	slice2: class extends self.ISpriteInstance {},
	slike2: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}