const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Behaviors.Persist,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{StorageData: 0},
	{Touch: 0},
	{arrowLeft: 0},
	{arrowRight: 0},
	{Tween: 0},
	{back_level: 0},
	{btn_back: 0},
	{btn_home: 0},
	{btn_info: 0},
	{Pin: 0},
	{btn_levels: 0},
	{btn_lvl: 0},
	{btn_more_games: 0},
	{btn_more_in: 0},
	{btn_more_t: 0},
	{btn_more_time: 0},
	{level: 0},
	{btn_next: 0},
	{btn_no: 0},
	{btn_play: 0},
	{btn_replay: 0},
	{btn_reset_game: 0},
	{btn_rw: 0},
	{btn_yes: 0},
	{btn_hint: 0},
	{frame: 0},
	{lv: 0},
	{btn_morehint: 0},
	{btn_continue: 0},
	{btn_music: 0},
	{btn_sound: 0},
	{bg: 0},
	{Sine: 0},
	{ch1: 0},
	{Sine2: 0},
	{lup: 0},
	{Rotate: 0},
	{rotate_effect: 0},
	{title: 0},
	{txt_tutorial: 0},
	{desb: 0},
	{rewardBlock: 0},
	{LevelPlace: 0},
	{Completed: 0},
	{ch_shadow: 0},
	{ch2: 0},
	{debugLevels: 0},
	{images: 0},
	{info: 0},
	{mark_object: 0},
	{active: 0},
	{touchCorrec: 0},
	{top_timer: 0},
	{foundTxt: 0},
	{TimerTxt: 0},
	{board_find: 0},
	{bg_pause: 0},
	{timerUp: 0},
	{complete: 0},
	{Bullet: 0},
	{Fade: 0},
	{subTimer: 0},
	{black: 0},
	{debug: 0},
	{Particles: 0},
	{position0: 0},
	{position1: 0},
	{ScrollTo: 0},
	{cam: 0},
	{board_level: 0},
	{select_txt: 0},
	{mark: 0},
	{logo: 0},
	{high_light: 0},
	{NumLevel: 0},
	{Stars: 0},
	{StarsLevels: 0},
	{StarsBar: 0},
	{LevelNumber: 0},
	{sky: 0},
	{number: 0},
	{Timer: 0},
	{star_burst: 0},
	{firefly: 0},
	{inblack: 0},
	{outblack: 0},
	{X: 0},
	{Wrongtap: 0},
	{minusval: 0},
	{Score_Font: 0},
	{Top_Score_Font: 0},
	{board_score: 0},
	{Confetti: 0},
	{ConfettiWinParticle: 0},
	{Persist: 0},
	{FireSparkParticlesHeart: 0},
	{FireSparkParticlesFound: 0},
	{prasal: 0},
	{bg_topscore: 0},
	{GameMonetizeSDK: 0},
	{tap: 0},
	{Melody: 0},
	{lsRewards: 0},
	{lsName: 0},
	{found: 0},
	{click1: 0},
	{click2: 0},
	{StopCheat: 0},
	{Desb: 0},
	{count: 0},
	{GameOver: 0},
	{Score: 0},
	{Top_Score: 0},
	{timerCount: 0},
	{touch: 0},
	{wait: 0},
	{CurrentStars: 0},
	{Levels: 0},
	{CompletedLevels: 0},
	{Win: 0},
	{intract: 0},
	{CurrentLevel: 0},
	{playbleLevel: 0},
	{StarsLevel1: 0},
	{StarsLevel2: 0},
	{StarsLevel3: 0},
	{StarsLevel4: 0},
	{StarsLevel5: 0},
	{StarsLevel6: 0},
	{StarsLevel7: 0},
	{StarsLevel8: 0},
	{StarsLevel9: 0},
	{StarsLevel10: 0},
	{StarsLevel11: 0},
	{StarsLevel12: 0},
	{StarsLevel13: 0},
	{StarsLevel14: 0},
	{StarsLevel15: 0},
	{StarsLevel16: 0},
	{StarsLevel17: 0},
	{StarsLevel18: 0},
	{StarsLevel19: 0},
	{StarsLevel20: 0},
	{StarsLevel21: 0},
	{StarsLevel22: 0},
	{StarsLevel23: 0},
	{StarsLevel24: 0},
	{StarsLevel25: 0},
	{StarsLevel26: 0},
	{StarsLevel27: 0},
	{StarsLevel28: 0},
	{StarsLevel29: 0},
	{StarsLevel30: 0},
	{CamPos: 0},
	{Sound: 0},
	{Music: 0},
	{Sound_Volume: 0},
	{Type: 0},
	{GAME_NAME: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	StorageData: class extends self.IDictionaryInstance {},
	Touch: class extends self.IInstance {},
	arrowLeft: class extends self.ISpriteInstance {},
	arrowRight: class extends self.ISpriteInstance {},
	back_level: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	btn_levels: class extends self.ISpriteInstance {},
	btn_lvl: class extends self.ISpriteInstance {},
	btn_more_games: class extends self.ISpriteInstance {},
	btn_more_in: class extends self.ISpriteInstance {},
	btn_more_t: class extends self.ISpriteInstance {},
	btn_more_time: class extends self.ISpriteInstance {},
	btn_next: class extends self.ISpriteInstance {},
	btn_no: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_replay: class extends self.ISpriteInstance {},
	btn_reset_game: class extends self.ISpriteInstance {},
	btn_rw: class extends self.ISpriteInstance {},
	btn_yes: class extends self.ISpriteInstance {},
	btn_hint: class extends self.ISpriteInstance {},
	lv: class extends self.ISpriteInstance {},
	btn_morehint: class extends self.ISpriteInstance {},
	btn_continue: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	ch1: class extends self.ISpriteInstance {},
	lup: class extends self.ISpriteInstance {},
	rotate_effect: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	txt_tutorial: class extends self.ISpriteInstance {},
	rewardBlock: class extends self.ISpriteInstance {},
	LevelPlace: class extends self.ISpriteInstance {},
	Completed: class extends self.ISpriteFontInstance {},
	ch_shadow: class extends self.ISpriteInstance {},
	ch2: class extends self.ISpriteInstance {},
	debugLevels: class extends self.ITextInstance {},
	images: class extends self.ISpriteInstance {},
	mark_object: class extends self.ISpriteInstance {},
	touchCorrec: class extends self.ISpriteInstance {},
	top_timer: class extends self.ISpriteInstance {},
	foundTxt: class extends self.ISpriteFontInstance {},
	TimerTxt: class extends self.ISpriteFontInstance {},
	board_find: class extends self.ISpriteInstance {},
	bg_pause: class extends self.ISpriteInstance {},
	timerUp: class extends self.ISpriteInstance {},
	complete: class extends self.ISpriteInstance {},
	subTimer: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	debug: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	cam: class extends self.ISpriteInstance {},
	board_level: class extends self.ISpriteInstance {},
	select_txt: class extends self.ISpriteInstance {},
	mark: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	high_light: class extends self.IParticlesInstance {},
	StarsLevels: class extends self.ISpriteInstance {},
	StarsBar: class extends self.ISpriteInstance {},
	LevelNumber: class extends self.ISpriteFontInstance {},
	sky: class extends self.ISpriteInstance {},
	star_burst: class extends self.ISpriteInstance {},
	firefly: class extends self.ISpriteInstance {},
	inblack: class extends self.ISpriteInstance {},
	outblack: class extends self.ISpriteInstance {},
	X: class extends self.ISpriteInstance {},
	Wrongtap: class extends self.ISpriteInstance {},
	minusval: class extends self.ISpriteInstance {},
	Score_Font: class extends self.ISpriteFontInstance {},
	Top_Score_Font: class extends self.ISpriteFontInstance {},
	board_score: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	ConfettiWinParticle: class extends self.IParticlesInstance {},
	FireSparkParticlesHeart: class extends self.IParticlesInstance {},
	FireSparkParticlesFound: class extends self.IParticlesInstance {},
	prasal: class extends self.ISpriteInstance {},
	bg_topscore: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	tap: class extends self.ISpriteInstance {}
}