const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.ScriptsInEvents._2players_es_Event67_Act1,
		C3.ScriptsInEvents._2players_es_Event69_Act1,
		C3.ScriptsInEvents._2players_es_Event76_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Button.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Text.Acts.SetText,
		C3.ScriptsInEvents.Ai_es_Event141_Act1,
		C3.ScriptsInEvents.Ai_es_Event148_Act1,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{disabled: 0},
	{box_value: 0},
	{tic_box1: 0},
	{tic_box2: 0},
	{tic_box3: 0},
	{tic_box4: 0},
	{tic_box5: 0},
	{tic_box6: 0},
	{tic_box7: 0},
	{tic_box8: 0},
	{tic_box9: 0},
	{BG_Game: 0},
	{boardArtboard: 0},
	{Button_Home: 0},
	{Button_Sound: 0},
	{Friend_text: 0},
	{profileArtboard: 0},
	{profileArtboard2: 0},
	{rectangle1Artboard: 0},
	{TickBox_Enemy: 0},
	{TickBox_Self: 0},
	{Touch: 0},
	{youAsset: 0},
	{AI_tic_box1: 0},
	{AI_tic_box2: 0},
	{AI_tic_box3: 0},
	{AI_tic_box4: 0},
	{AI_tic_box5: 0},
	{AI_tic_box6: 0},
	{AI_tic_box7: 0},
	{AI_tic_box8: 0},
	{AI_tic_box9: 0},
	{b1: 0},
	{b2: 0},
	{b3: 0},
	{b4: 0},
	{b5: 0},
	{b6: 0},
	{b7: 0},
	{b8: 0},
	{b9: 0},
	{Button3: 0},
	{restart: 0},
	{Text4: 0},
	{plaAsset: 0},
	{Game_Mode_BG: 0},
	{GameModeBoardAsset: 0},
	{GameModeTextAsset: 0},
	{Tween: 0},
	{playComputerAsset: 0},
	{playFriendsAsset: 0},
	{AI_Button: 0},
	{"2_Player_Button": 0},
	{winSquare: 0},
	{loseSquare: 0},
	{winLoseTieBgAsset: 0},
	{gameTieAsset: 0},
	{winSunrayAsset: 0},
	{me_pp: 0},
	{frnd_pp: 0},
	{c4Asset: 0},
	{youWinAsset: 0},
	{youLoseAsset: 0},
	{MainMenuBgArtboard2Copy: 0},
	{ButtonsArtboard: 0},
	{playButtonAsset: 0},
	{santaAsset: 0},
	{SnowArtboard: 0},
	{GameTitleAsset: 0},
	{Browser: 0},
	{Audio: 0},
	{Sprite: 0},
	{TieAsset: 0},
	{GameMonetizeSDK: 0},
	{turn: 0},
	{"2_b1": 0},
	{"2_b2": 0},
	{"2_b3": 0},
	{"2_b4": 0},
	{"2_b5": 0},
	{"2_b6": 0},
	{"2_b7": 0},
	{"2_b8": 0},
	{"2_b9": 0},
	{"2X1": 0},
	{"2X2": 0},
	{"2X3": 0},
	{"2Y1": 0},
	{"2Y2": 0},
	{"2Y3": 0},
	{"2XX1": 0},
	{"2XX2": 0},
	{current_round: 0},
	{Y1: 0},
	{Y2: 0},
	{Y3: 0},
	{X1: 0},
	{X2: 0},
	{X3: 0},
	{XX1: 0},
	{XX2: 0},
	{RA: 0},
	{done: 0},
	{steps: 0},
	{PLAYING_AI: 0},
	{ai_turn: 0},
	{game_end: 0},
	{round1: 0},
	{round2: 0},
	{round3: 0},
	{round4: 0},
	{round5: 0}
];

self.InstanceType = {
	tic_box1: class extends self.ISpriteInstance {},
	tic_box2: class extends self.ISpriteInstance {},
	tic_box3: class extends self.ISpriteInstance {},
	tic_box4: class extends self.ISpriteInstance {},
	tic_box5: class extends self.ISpriteInstance {},
	tic_box6: class extends self.ISpriteInstance {},
	tic_box7: class extends self.ISpriteInstance {},
	tic_box8: class extends self.ISpriteInstance {},
	tic_box9: class extends self.ISpriteInstance {},
	BG_Game: class extends self.ISpriteInstance {},
	boardArtboard: class extends self.ISpriteInstance {},
	Button_Home: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	Friend_text: class extends self.ISpriteInstance {},
	profileArtboard: class extends self.ISpriteInstance {},
	profileArtboard2: class extends self.ISpriteInstance {},
	rectangle1Artboard: class extends self.ISpriteInstance {},
	TickBox_Enemy: class extends self.ISpriteInstance {},
	TickBox_Self: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	youAsset: class extends self.ISpriteInstance {},
	AI_tic_box1: class extends self.ISpriteInstance {},
	AI_tic_box2: class extends self.ISpriteInstance {},
	AI_tic_box3: class extends self.ISpriteInstance {},
	AI_tic_box4: class extends self.ISpriteInstance {},
	AI_tic_box5: class extends self.ISpriteInstance {},
	AI_tic_box6: class extends self.ISpriteInstance {},
	AI_tic_box7: class extends self.ISpriteInstance {},
	AI_tic_box8: class extends self.ISpriteInstance {},
	AI_tic_box9: class extends self.ISpriteInstance {},
	b1: class extends self.IButtonInstance {},
	b2: class extends self.IButtonInstance {},
	b3: class extends self.IButtonInstance {},
	b4: class extends self.IButtonInstance {},
	b5: class extends self.IButtonInstance {},
	b6: class extends self.IButtonInstance {},
	b7: class extends self.IButtonInstance {},
	b8: class extends self.IButtonInstance {},
	b9: class extends self.IButtonInstance {},
	Button3: class extends self.IButtonInstance {},
	restart: class extends self.IButtonInstance {},
	Text4: class extends self.ITextInstance {},
	plaAsset: class extends self.ISpriteInstance {},
	Game_Mode_BG: class extends self.ISpriteInstance {},
	GameModeBoardAsset: class extends self.ISpriteInstance {},
	GameModeTextAsset: class extends self.ISpriteInstance {},
	playComputerAsset: class extends self.ISpriteInstance {},
	playFriendsAsset: class extends self.ISpriteInstance {},
	AI_Button: class extends self.IButtonInstance {},
	_2_Player_Button: class extends self.IButtonInstance {},
	winSquare: class extends self.ISpriteInstance {},
	loseSquare: class extends self.ISpriteInstance {},
	winLoseTieBgAsset: class extends self.ISpriteInstance {},
	gameTieAsset: class extends self.ISpriteInstance {},
	winSunrayAsset: class extends self.ISpriteInstance {},
	me_pp: class extends self.ISpriteInstance {},
	frnd_pp: class extends self.ISpriteInstance {},
	c4Asset: class extends self.ISpriteInstance {},
	youWinAsset: class extends self.ISpriteInstance {},
	youLoseAsset: class extends self.ISpriteInstance {},
	MainMenuBgArtboard2Copy: class extends self.ISpriteInstance {},
	ButtonsArtboard: class extends self.ISpriteInstance {},
	playButtonAsset: class extends self.ISpriteInstance {},
	santaAsset: class extends self.ISpriteInstance {},
	SnowArtboard: class extends self.ISpriteInstance {},
	GameTitleAsset: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TieAsset: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}