const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Physics,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.FileSystem,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.GM_SDK,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{Exit_btn: 0},
	{LevelUnlocked_text_sprite: 0},
	{Tween: 0},
	{Play_btn: 0},
	{Title: 0},
	{level_id: 0},
	{level_btn: 0},
	{level_text_sprite: 0},
	{level_btn_playground: 0},
	{touch_area: 0},
	{counted: 0},
	{Physics: 0},
	{Ball: 0},
	{bucket: 0},
	{bucket_collision: 0},
	{SpriteFont_level: 0},
	{level_headline: 0},
	{SpriteFont_level_main_menu: 0},
	{Flash: 0},
	{SpriteFont_level_score: 0},
	{obstacle_wall: 0},
	{type: 0},
	{obstacle_cutter: 0},
	{level_failed: 0},
	{level_complete: 0},
	{next_lvl: 0},
	{RESTART_BTN: 0},
	{MY_SCORE_TEXT: 0},
	{MY_SCORE_TEXT_BG: 0},
	{HIGH_SCORE_TEXT: 0},
	{HIGH_SCORE_TEXT_BG: 0},
	{SpriteFont__score: 0},
	{SpriteFont_high_score: 0},
	{last_black_screen_to_switch: 0},
	{BG: 0},
	{SpriteFont_levelmenu: 0},
	{Touch: 0},
	{complete_the_bar: 0},
	{progress_bg: 0},
	{progress_fg: 0},
	{life_text: 0},
	{life_id: 0},
	{heart_icn: 0},
	{Sprite: 0},
	{home_btn: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{touch_sprite: 0},
	{Browser: 0},
	{sound_btn: 0},
	{FileSystem: 0},
	{Keyboard: 0},
	{Particles: 0},
	{confetti_obj: 0},
	{GameMonetizeSDK: 0},
	{score: 0},
	{highscore: 0},
	{midshift_x: 0},
	{midshift_y: 0},
	{most_level: 0},
	{ball_in_bucket: 0},
	{can_emit: 0},
	{life_amount: 0},
	{level_index: 0},
	{play_state: 0},
	{clickable: 0},
	{level_score: 0}
];

self.InstanceType = {
	Exit_btn: class extends self.ISpriteInstance {},
	LevelUnlocked_text_sprite: class extends self.ISpriteInstance {},
	Play_btn: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	level_btn: class extends self.ISpriteInstance {},
	level_text_sprite: class extends self.ISpriteInstance {},
	level_btn_playground: class extends self.ISpriteInstance {},
	touch_area: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	bucket: class extends self.ISpriteInstance {},
	bucket_collision: class extends self.ISpriteInstance {},
	SpriteFont_level: class extends self.ISpriteFontInstance {},
	level_headline: class extends self.ISpriteInstance {},
	SpriteFont_level_main_menu: class extends self.ISpriteFontInstance {},
	SpriteFont_level_score: class extends self.ISpriteFontInstance {},
	obstacle_wall: class extends self.ISpriteInstance {},
	obstacle_cutter: class extends self.ISpriteInstance {},
	level_failed: class extends self.ISpriteInstance {},
	level_complete: class extends self.ISpriteInstance {},
	next_lvl: class extends self.ISpriteInstance {},
	RESTART_BTN: class extends self.ISpriteInstance {},
	MY_SCORE_TEXT: class extends self.ISpriteInstance {},
	MY_SCORE_TEXT_BG: class extends self.ISpriteInstance {},
	HIGH_SCORE_TEXT: class extends self.ISpriteInstance {},
	HIGH_SCORE_TEXT_BG: class extends self.ISpriteInstance {},
	SpriteFont__score: class extends self.ISpriteFontInstance {},
	SpriteFont_high_score: class extends self.ISpriteFontInstance {},
	last_black_screen_to_switch: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	SpriteFont_levelmenu: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	complete_the_bar: class extends self.ISpriteInstance {},
	progress_bg: class extends self.ISpriteInstance {},
	progress_fg: class extends self.ISpriteInstance {},
	life_text: class extends self.ISpriteInstance {},
	heart_icn: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	home_btn: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	touch_sprite: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	sound_btn: class extends self.ISpriteInstance {},
	FileSystem: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	confetti_obj: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}