const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.AJAX,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Flash,
		C3.Plugins.Arr,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.NinePatch,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Tilemap.Exps.X,
		C3.Plugins.Tilemap.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Tilemap.Exps.Width,
		C3.Plugins.Tilemap.Exps.Height,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgb,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.DrawingCanvas.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Exps.X,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.IID,
		C3.Behaviors.TileMovement.Cnds.CanMoveDirection,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Exps.TouchIndex,
		C3.Behaviors.TileMovement.Cnds.IsEnabled,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Exps.projectversion,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.zeropad,
		C3.Behaviors.Tween.Cnds.OnTweensFinished
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{intro_: 0},
	{Sine: 0},
	{txt_taptocontinue: 0},
	{Touch: 0},
	{debug: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{fade: 0},
	{txt_reset: 0},
	{Anchor: 0},
	{btn_main: 0},
	{btn_sound: 0},
	{btn_music: 0},
	{bgPaused: 0},
	{b_play: 0},
	{txt_ver: 0},
	{txt_score: 0},
	{fontSizeDefault: 0},
	{txt_gameover: 0},
	{Tween: 0},
	{btn_restartGame: 0},
	{btn_restart: 0},
	{btn_fullscreen: 0},
	{btn_info: 0},
	{txt_infoBack: 0},
	{title: 0},
	{Browser: 0},
	{colorName: 0},
	{smallSize: 0},
	{music: 0},
	{Pin: 0},
	{txt_credits: 0},
	{txt_howTo: 0},
	{Rotate: 0},
	{part_sprite: 0},
	{part_sucess: 0},
	{lv: 0},
	{memPos: 0},
	{btn_level: 0},
	{txt_label: 0},
	{txt_btnLevel: 0},
	{AJAX: 0},
	{Keyboard: 0},
	{tapOk: 0},
	{txt_tapToNext: 0},
	{p_end: 0},
	{Solid: 0},
	{wallsSize1: 0},
	{countToMatch: 0},
	{correctAngle: 0},
	{TileMovement: 0},
	{block: 0},
	{frame: 0},
	{counter: 0},
	{checkNeighbors: 0},
	{match: 0},
	{bgLines: 0},
	{Flash: 0},
	{noMatch: 0},
	{a_blocks: 0},
	{lv_locked: 0},
	{hand: 0},
	{block_draw: 0},
	{howToBlock: 0},
	{"9patch": 0},
	{GameMonetizeSDK: 0},
	{TopButtons: 0},
	{load_ok: 0},
	{storageName: 0},
	{score: 0},
	{hScore: 0},
	{progressLevel: 0},
	{movingBlockIID: 0},
	{selectedTouchIID: 0},
	{movingDirection: 0},
	{lastMove: 0},
	{color: 0},
	{value: 0},
	{win: 0},
	{Sound: 0},
	{Music: 0},
	{fadeTime: 0},
	{in: 0},
	{control: 0},
	{levelsCount: 0}
];

self.InstanceType = {
	intro_: class extends self.ISpriteInstance {},
	txt_taptocontinue: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	debug: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	txt_reset: class extends self.ITextInstance {},
	btn_main: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	bgPaused: class extends self.ITiledBackgroundInstance {},
	b_play: class extends self.ISpriteInstance {},
	txt_ver: class extends self.ITextInstance {},
	txt_score: class extends self.ITextInstance {},
	txt_gameover: class extends self.ITextInstance {},
	btn_restartGame: class extends self.ISpriteInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	btn_fullscreen: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	txt_infoBack: class extends self.ITextInstance {},
	title: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	txt_credits: class extends self.ITextInstance {},
	txt_howTo: class extends self.ITextInstance {},
	part_sprite: class extends self.ISpriteInstance {},
	part_sucess: class extends self.IParticlesInstance {},
	btn_level: class extends self.ISpriteInstance {},
	txt_label: class extends self.ITextInstance {},
	txt_btnLevel: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	txt_tapToNext: class extends self.ITextInstance {},
	p_end: class extends self.IParticlesInstance {},
	wallsSize1: class extends self.ITilemapInstance {},
	block: class extends self.ISpriteInstance {},
	checkNeighbors: class extends self.ISpriteInstance {},
	match: class extends self.ISpriteInstance {},
	bgLines: class extends self.ITiledBackgroundInstance {},
	noMatch: class extends self.ISpriteInstance {},
	a_blocks: class extends self.IArrayInstance {},
	lv_locked: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	block_draw: class extends self.IDrawingCanvasInstance {},
	howToBlock: class extends self.IDrawingCanvasInstance {},
	_9patch: class extends self.IWorldInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	TopButtons: class extends self.ISpriteInstance {}
}