const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.ScriptsInEvents["Onstart-E_Event4_Act1"],
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Bgs: 0},
	{Tween: 0},
	{Patterns_1: 0},
	{Patterns_2: 0},
	{Sine: 0},
	{Sine2: 0},
	{Flags: 0},
	{Pin: 0},
	{Loader_back: 0},
	{Loader: 0},
	{Crt_Ans: 0},
	{Optional_btn1: 0},
	{Optional_btn2: 0},
	{Optional_btn3: 0},
	{Dark: 0},
	{Conditional_dark: 0},
	{LoaderPad: 0},
	{Clock: 0},
	{Tweenerr: 0},
	{Opacity: 0},
	{Languages: 0},
	{Browser: 0},
	{Touch: 0},
	{Flag_Once: 0},
	{AJAX: 0},
	{Flag_names: 0},
	{Btn_Array: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{GameMonetizeSDK: 0},
	{Text1: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Level: 0},
	{Curr_Lev: 0},
	{Seconds: 0},
	{Score: 0},
	{HighScore: 0},
	{Text_Score: 0},
	{Curr_Lev2: 0},
	{Home: 0},
	{Volume: 0},
	{Refresh: 0},
	{Fail: 0},
	{Fail_replay: 0},
	{Replay: 0},
	{Fail_panel: 0},
	{Final_home: 0},
	{Final_replay: 0},
	{Completed_Tick: 0},
	{Update: 0},
	{Pointer: 0},
	{Pointer2: 0},
	{Mover_1: 0},
	{Mover_2: 0},
	{Mover_3: 0},
	{Collider: 0},
	{Game_mode: 0},
	{Streak: 0},
	{"60Sec": 0},
	{Learn: 0},
	{High: 0},
	{Game_Over: 0},
	{Flag1: 0},
	{Flag2: 0},
	{Flag: 0},
	{Guess: 0},
	{The: 0},
	{Bg_pad: 0},
	{Shadow: 0},
	{Logo_Flag: 0},
	{Yellow_Star: 0},
	{Star: 0},
	{WhiteStr: 0},
	{Play_btn: 0},
	{Bags: 0},
	{play_btn2: 0},
	{Eng_btn: 0},
	{Spanish_btn: 0},
	{Turkey_btn: 0},
	{Russia_btn: 0},
	{Brazil: 0},
	{icon: 0},
	{UiSounds: 0},
	{Flag_Fam: 0},
	{Loader_width: 0},
	{Pick_random: 0},
	{Pick_random2: 0},
	{Show_Score: 0},
	{Show_60_sec_Score: 0},
	{Show_Learn_Score: 0},
	{New_To_page: 0},
	{Final_Loader_width: 0},
	{Flag_round_1: 0},
	{Loader_X: 0},
	{Loader_Y: 0},
	{Second: 0},
	{Tot_Score: 0},
	{Tot_Score_60_sec: 0},
	{Tot_Score_Learn: 0},
	{Button1: 0},
	{Button2: 0},
	{Button3: 0},
	{Button_pic: 0},
	{Button_pic_Count: 0},
	{Win: 0},
	{"60_Win": 0},
	{Learn_Win: 0},
	{"60_Over": 0},
	{"60_Fail": 0},
	{Learn_Fail: 0},
	{Btn_Set: 0},
	{After_Check: 0},
	{Button_2_val: 0},
	{Button_3_val: 0},
	{Live_Lev_Streak: 0},
	{Live_Lev_60_Sec: 0},
	{Live_Lev_Learn: 0},
	{Sixty_Sec: 0},
	{Local_Store: 0},
	{Sound: 0},
	{Ad_mute: 0},
	{Ad_time: 0},
	{Time_bet: 0},
	{Top_Current_frame: 0},
	{Bottom_Current_frame: 0},
	{Flag_Speed: 0},
	{Time_Create: 0},
	{Language: 0},
	{Paused: 0}
];

self.InstanceType = {
	Bgs: class extends self.ISpriteInstance {},
	Patterns_1: class extends self.ISpriteInstance {},
	Patterns_2: class extends self.ISpriteInstance {},
	Flags: class extends self.ISpriteInstance {},
	Loader_back: class extends self.ISpriteInstance {},
	Loader: class extends self.ISpriteInstance {},
	Optional_btn1: class extends self.ISpriteInstance {},
	Optional_btn2: class extends self.ISpriteInstance {},
	Optional_btn3: class extends self.ISpriteInstance {},
	Dark: class extends self.ISpriteInstance {},
	Conditional_dark: class extends self.ISpriteInstance {},
	LoaderPad: class extends self.ISpriteInstance {},
	Clock: class extends self.ISpriteInstance {},
	Tweenerr: class extends self.ISpriteInstance {},
	Opacity: class extends self.ISpriteInstance {},
	Languages: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Flag_Once: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Flag_names: class extends self.IArrayInstance {},
	Btn_Array: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	GameMonetizeSDK: class extends C3.Plugins.GM_SDK.Instance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Level: class extends self.ISpriteFontInstance {},
	Curr_Lev: class extends self.ISpriteFontInstance {},
	Seconds: class extends self.ISpriteFontInstance {},
	Score: class extends self.ISpriteFontInstance {},
	HighScore: class extends self.ISpriteFontInstance {},
	Text_Score: class extends self.ITextInstance {},
	Curr_Lev2: class extends self.ISpriteFontInstance {},
	Home: class extends self.ISpriteInstance {},
	Volume: class extends self.ISpriteInstance {},
	Refresh: class extends self.ISpriteInstance {},
	Fail: class extends self.ISpriteInstance {},
	Fail_replay: class extends self.ISpriteInstance {},
	Replay: class extends self.ISpriteInstance {},
	Fail_panel: class extends self.ISpriteInstance {},
	Final_home: class extends self.ISpriteInstance {},
	Final_replay: class extends self.ISpriteInstance {},
	Completed_Tick: class extends self.ISpriteInstance {},
	Update: class extends self.ISpriteInstance {},
	Pointer: class extends self.ISpriteInstance {},
	Pointer2: class extends self.ISpriteInstance {},
	Mover_1: class extends self.ISpriteInstance {},
	Mover_2: class extends self.ISpriteInstance {},
	Mover_3: class extends self.ISpriteInstance {},
	Collider: class extends self.ISpriteInstance {},
	Game_mode: class extends self.ISpriteInstance {},
	Streak: class extends self.ISpriteInstance {},
	_60Sec: class extends self.ISpriteInstance {},
	Learn: class extends self.ISpriteInstance {},
	High: class extends self.ISpriteInstance {},
	Game_Over: class extends self.ISpriteInstance {},
	Flag1: class extends self.ISpriteInstance {},
	Flag2: class extends self.ISpriteInstance {},
	Flag: class extends self.ISpriteInstance {},
	Guess: class extends self.ISpriteInstance {},
	The: class extends self.ISpriteInstance {},
	Bg_pad: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	Logo_Flag: class extends self.ISpriteInstance {},
	Yellow_Star: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	WhiteStr: class extends self.ISpriteInstance {},
	Play_btn: class extends self.ISpriteInstance {},
	Bags: class extends self.ISpriteInstance {},
	play_btn2: class extends self.ISpriteInstance {},
	Eng_btn: class extends self.ISpriteInstance {},
	Spanish_btn: class extends self.ISpriteInstance {},
	Turkey_btn: class extends self.ISpriteInstance {},
	Russia_btn: class extends self.ISpriteInstance {},
	Brazil: class extends self.ISpriteInstance {},
	icon: class extends self.ISpriteInstance {},
	UiSounds: class extends self.ISpriteInstance {},
	Flag_Fam: class extends self.ISpriteInstance {}
}