const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.SVGPicture,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Behaviors.DragnDrop,
		C3.Plugins.progressbar,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.GM_SDK,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.progressbar.Acts.SetVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.LoadLayoutTextures,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Imgs: 0},
	{Img_canvas: 0},
	{Var: 0},
	{Mark: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Mark2: 0},
	{Array_MarkPosition: 0},
	{AJAX: 0},
	{BG: 0},
	{Back: 0},
	{lives: 0},
	{Tween: 0},
	{Asset: 0},
	{Hint: 0},
	{TimerText: 0},
	{Wrong: 0},
	{Array_Time: 0},
	{Slidebar: 0},
	{DragDrop: 0},
	{Slidebutton: 0},
	{Cam: 0},
	{SlideBG: 0},
	{ProgressBar: 0},
	{BG2: 0},
	{Board: 0},
	{LevelText: 0},
	{Tittle: 0},
	{Replay: 0},
	{Play: 0},
	{Music: 0},
	{BG3: 0},
	{Solid: 0},
	{Asset2: 0},
	{Platform: 0},
	{Asset3: 0},
	{www: 0},
	{GameMonetizeSDK: 0},
	{more: 0},
	{Browser: 0},
	{Marks: 0},
	{Bgs: 0},
	{UI: 0},
	{F1: 0},
	{chk: 0},
	{Win: 0},
	{Lose: 0},
	{CountMark: 0},
	{Try: 0},
	{Timer: 0},
	{distanceDifference: 0},
	{PrevSpeed: 0},
	{dSpeed: 0},
	{dangle: 0},
	{Slide_Touch: 0},
	{inter: 0}
];

self.InstanceType = {
	Imgs: class extends self.ISpriteInstance {},
	Img_canvas: class extends self.ISVGPictureInstance {},
	Mark: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mark2: class extends self.ISpriteInstance {},
	Array_MarkPosition: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	Back: class extends self.ISpriteInstance {},
	lives: class extends self.ISpriteInstance {},
	Asset: class extends self.ISpriteInstance {},
	Hint: class extends self.ISpriteInstance {},
	TimerText: class extends self.ISpriteFontInstance {},
	Wrong: class extends self.ISpriteInstance {},
	Array_Time: class extends self.IArrayInstance {},
	Slidebar: class extends self.ISpriteInstance {},
	Slidebutton: class extends self.ISpriteInstance {},
	Cam: class extends self.ISpriteInstance {},
	SlideBG: class extends self.ITiledBackgroundInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	Board: class extends self.ISpriteInstance {},
	LevelText: class extends self.ISpriteFontInstance {},
	Tittle: class extends self.ISpriteInstance {},
	Replay: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Music: class extends self.ISpriteInstance {},
	BG3: class extends self.ITiledBackgroundInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	www: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	more: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Marks: class extends self.ISpriteInstance {},
	Bgs: class extends self.ITiledBackgroundInstance {},
	UI: class extends self.ISpriteInstance {},
	F1: class extends self.ISpriteInstance {}
}