const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Plugins.Button,
		C3.Plugins.Share,
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Share.Cnds.IsSharingFilesSupported,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Share.Acts.AddFile,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.Sprite.Acts.SetMeshSize,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Exps.MeshColumns,
		C3.Plugins.Sprite.Exps.MeshRows,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Pin.Acts.PinByImagePoint
	];
};
self.C3_JsPropNameTable = [
	{Piggy: 0},
	{MeshColumn: 0},
	{MeshRow: 0},
	{DragDrop: 0},
	{MeshPoint: 0},
	{Text: 0},
	{idemodalje: 0},
	{Touch: 0},
	{Pin: 0},
	{ScreenshotSprite: 0},
	{TakeScreenshotButton: 0},
	{DownloadButton: 0},
	{ShareButton: 0},
	{Share: 0},
	{ShareStatus: 0},
	{AJAX: 0},
	{BinaryData: 0},
	{Browser: 0},
	{downloadbtn: 0},
	{takeshot: 0},
	{sharebtn: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{sharebtn2: 0},
	{hidedots: 0},
	{hidedots2: 0},
	{SpriteFont: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sine: 0},
	{PLAY: 0},
	{Sprite7: 0},
	{reset: 0},
	{Sprite8: 0},
	{trump: 0},
	{Sprite9: 0},
	{biden: 0},
	{Sprite10: 0},
	{HOME: 0},
	{putin: 0},
	{djokovic: 0},
	{lopez: 0},
	{ronaldo: 0},
	{more: 0},
	{Mouse: 0},
	{Sprite12: 0},
	{HOME2: 0},
	{BSound: 0},
	{Audio: 0},
	{y8: 0},
	{rusplese: 0},
	{Sprite11: 0},
	{Sprite13: 0},
	{cipele: 0},
	{cipele2: 0},
	{cipele3: 0},
	{cipele4: 0},
	{cipele5: 0},
	{cipele6: 0},
	{Sprite: 0},
	{kim: 0},
	{zlatan: 0},
	{y8profile: 0},
	{Loginy8moja: 0},
	{playerName: 0},
	{GameMonetizeSDK: 0},
	{buttons: 0},
	{PiggyLeft: 0},
	{PiggyTop: 0},
	{PiggyRight: 0},
	{PiggyBottom: 0},
	{sound: 0},
	{SoundEf: 0}
];

self.InstanceType = {
	Piggy: class extends self.ISpriteInstance {},
	MeshPoint: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	idemodalje: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	ScreenshotSprite: class extends self.ISpriteInstance {},
	TakeScreenshotButton: class extends self.IButtonInstance {},
	DownloadButton: class extends self.IButtonInstance {},
	ShareButton: class extends self.IButtonInstance {},
	Share: class extends self.IInstance {},
	ShareStatus: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Browser: class extends self.IInstance {},
	downloadbtn: class extends self.ISpriteInstance {},
	takeshot: class extends self.ISpriteInstance {},
	sharebtn: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	sharebtn2: class extends self.ISpriteInstance {},
	hidedots: class extends self.ISpriteInstance {},
	hidedots2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	PLAY: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	reset: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	trump: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	biden: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	HOME: class extends self.ISpriteInstance {},
	putin: class extends self.ISpriteInstance {},
	djokovic: class extends self.ISpriteInstance {},
	lopez: class extends self.ISpriteInstance {},
	ronaldo: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	HOME2: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	y8: class extends self.ISpriteInstance {},
	rusplese: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	cipele: class extends self.ISpriteInstance {},
	cipele2: class extends self.ISpriteInstance {},
	cipele3: class extends self.ISpriteInstance {},
	cipele4: class extends self.ISpriteInstance {},
	cipele5: class extends self.ISpriteInstance {},
	cipele6: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	kim: class extends self.ISpriteInstance {},
	zlatan: class extends self.ISpriteInstance {},
	y8profile: class extends self.ISpriteInstance {},
	Loginy8moja: class extends self.ISpriteInstance {},
	playerName: class extends self.ITextInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	buttons: class extends self.ISpriteInstance {}
}