const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.NoSave,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Dictionary,
		C3.Plugins.Browser,
		C3.Plugins.advert,
		C3.Plugins.GM_SDK,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.MoveTo.Exps.Speed,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.MoveTo.Cnds.OnHitSolid,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.GM_SDK.Cnds.PauseGame
	];
};
self.C3_JsPropNameTable = [
	{zbg: 0},
	{ztile: 0},
	{Sine: 0},
	{BtnNEXT: 0},
	{Btns: 0},
	{sfLevel: 0},
	{target: 0},
	{gamename: 0},
	{level: 0},
	{BtnLvl: 0},
	{Fade: 0},
	{TextHint: 0},
	{sfLevelMn: 0},
	{moved: 0},
	{NoSave: 0},
	{undo: 0},
	{sfCoin: 0},
	{selectBall: 0},
	{shopBalls: 0},
	{price: 0},
	{Solid: 0},
	{BtnSkip: 0},
	{needmove: 0},
	{lastObj: 0},
	{lastCount: 0},
	{Ball1: 0},
	{Ball2: 0},
	{Ball3: 0},
	{Basket: 0},
	{LastOBJ: 0},
	{CHECKER: 0},
	{Tilemap: 0},
	{Prtcl_1: 0},
	{Prtcl_2: 0},
	{Prtcl_3: 0},
	{Box1: 0},
	{Box2: 0},
	{Coin: 0},
	{Keyboard: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{PlatformInfo: 0},
	{touchPos: 0},
	{touchStart: 0},
	{DDictionary: 0},
	{Browser: 0},
	{MobileAdvert: 0},
	{bg: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{GameMonetizeSDK: 0},
	{MoveTo: 0},
	{ALLMovers: 0},
	{BALLs: 0},
	{btnLEVELs: 0},
	{BOXs: 0},
	{CHECKs: 0},
	{Balls123: 0},
	{Game: 0},
	{movedir: 0},
	{touchAngle: 0},
	{sound: 0},
	{currentLevel: 0},
	{coin: 0},
	{BallType: 0},
	{IsAdRunning: 0}
];

self.InstanceType = {
	zbg: class extends self.ITiledBackgroundInstance {},
	ztile: class extends self.ITiledBackgroundInstance {},
	BtnNEXT: class extends self.ISpriteInstance {},
	Btns: class extends self.ISpriteInstance {},
	sfLevel: class extends self.ISpriteFontInstance {},
	target: class extends self.ISpriteInstance {},
	gamename: class extends self.ISpriteInstance {},
	BtnLvl: class extends self.ISpriteInstance {},
	TextHint: class extends self.ITextInstance {},
	sfLevelMn: class extends self.ISpriteFontInstance {},
	undo: class extends self.ISpriteInstance {},
	sfCoin: class extends self.ISpriteFontInstance {},
	selectBall: class extends self.ISpriteInstance {},
	shopBalls: class extends self.ISpriteInstance {},
	price: class extends self.ISpriteInstance {},
	BtnSkip: class extends self.ISpriteInstance {},
	Ball1: class extends self.ISpriteInstance {},
	Ball2: class extends self.ISpriteInstance {},
	Ball3: class extends self.ISpriteInstance {},
	Basket: class extends self.ISpriteInstance {},
	CHECKER: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Prtcl_1: class extends self.IParticlesInstance {},
	Prtcl_2: class extends self.IParticlesInstance {},
	Prtcl_3: class extends self.IParticlesInstance {},
	Box1: class extends self.ISpriteInstance {},
	Box2: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	touchPos: class extends self.ISpriteInstance {},
	touchStart: class extends self.ISpriteInstance {},
	DDictionary: class extends self.IDictionaryInstance {},
	Browser: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	bg: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	ALLMovers: class extends self.ISpriteInstance {},
	BALLs: class extends self.ISpriteInstance {},
	btnLEVELs: class extends self.ISpriteInstance {},
	BOXs: class extends self.ISpriteInstance {},
	CHECKs: class extends self.ISpriteInstance {},
	Balls123: class extends self.ISpriteInstance {}
}