const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Timeline,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.MoveTo.Acts.SetMovingAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{angleStart: 0},
	{angleTotal: 0},
	{Rotate: 0},
	{Tween: 0},
	{arrow: 0},
	{position: 0},
	{platform: 0},
	{pinON: 0},
	{gameover: 0},
	{Pin: 0},
	{MoveTo: 0},
	{Bullet: 0},
	{player: 0},
	{start: 0},
	{Touch: 0},
	{updown: 0},
	{arrowMask: 0},
	{playereffect: 0},
	{death: 0},
	{death2: 0},
	{startParticle: 0},
	{maskPlatform: 0},
	{Particles: 0},
	{LocalStorage: 0},
	{Score: 0},
	{Sine: 0},
	{BestScore: 0},
	{tutorialText: 0},
	{overDesk: 0},
	{playButton: 0},
	{Fade: 0},
	{fade: 0},
	{TextScore: 0},
	{TextBestScore: 0},
	{maskButton: 0},
	{logoUp: 0},
	{logoDown: 0},
	{Timeline: 0},
	{startMask: 0},
	{homeButton: 0},
	{Audio: 0},
	{www: 0},
	{GameMonetizeSDK: 0},
	{AllPlatform: 0},
	{OverMenu: 0},
	{SizePlatform: 0},
	{SizePlayer: 0},
	{Speed: 0},
	{HighScore: 0},
	{ScorePlus1: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	arrow: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	arrowMask: class extends self.ISpriteInstance {},
	playereffect: class extends self.ISpriteInstance {},
	death: class extends self.IParticlesInstance {},
	death2: class extends self.IParticlesInstance {},
	startParticle: class extends self.IParticlesInstance {},
	maskPlatform: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	LocalStorage: class extends self.IInstance {},
	Score: class extends self.ITextInstance {},
	BestScore: class extends self.ITextInstance {},
	tutorialText: class extends self.ITextInstance {},
	overDesk: class extends self.ISpriteInstance {},
	playButton: class extends self.ISpriteInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	TextScore: class extends self.ITextInstance {},
	TextBestScore: class extends self.ITextInstance {},
	maskButton: class extends self.ISpriteInstance {},
	logoUp: class extends self.ITextInstance {},
	logoDown: class extends self.ITextInstance {},
	Timeline: class extends self.IInstance {},
	startMask: class extends self.ISpriteInstance {},
	homeButton: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	www: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	AllPlatform: class extends self.ISpriteInstance {},
	OverMenu: class extends self.ITextInstance {}
}