const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Behaviors.MoveTo,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Timeline,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Timeline.Cnds.IsPlayingByTags,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{bar: 0},
	{blueball: 0},
	{damage: 0},
	{Tween: 0},
	{damageEffect: 0},
	{Fade: 0},
	{fadeLose: 0},
	{fadeOver: 0},
	{fadeWin: 0},
	{MoveTo: 0},
	{fullbar: 0},
	{greenball: 0},
	{levelOver: 0},
	{levelOverEffect: 0},
	{levelStart: 0},
	{lifeLine: 0},
	{oceanball: 0},
	{Particles: 0},
	{purpleball: 0},
	{rope: 0},
	{rope2: 0},
	{sight: 0},
	{blink: 0},
	{effectStart: 0},
	{logo: 0},
	{startbutton: 0},
	{boardOver: 0},
	{homeButton: 0},
	{Sine: 0},
	{playButton: 0},
	{Touch: 0},
	{Timeline: 0},
	{level: 0},
	{levelNext: 0},
	{textLevel: 0},
	{textLifeLine: 0},
	{textCompleted: 0},
	{Score: 0},
	{textMaximum: 0},
	{tBestScore: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{www: 0},
	{more: 0},
	{Browser: 0},
	{home: 0},
	{GameMonetizeSDK: 0},
	{Balls: 0},
	{OverObject: 0},
	{OverText: 0},
	{Level: 0},
	{LevelNext: 0},
	{LevelDamage: 0},
	{TimeSight: 0},
	{Life: 0},
	{LevelCompleted: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	bar: class extends self.ISpriteInstance {},
	blueball: class extends self.ISpriteInstance {},
	damage: class extends self.ISpriteInstance {},
	damageEffect: class extends self.ISpriteInstance {},
	fadeLose: class extends self.ITiledBackgroundInstance {},
	fadeOver: class extends self.ITiledBackgroundInstance {},
	fadeWin: class extends self.ITiledBackgroundInstance {},
	fullbar: class extends self.ISpriteInstance {},
	greenball: class extends self.ISpriteInstance {},
	levelOver: class extends self.ISpriteInstance {},
	levelOverEffect: class extends self.ISpriteInstance {},
	levelStart: class extends self.ISpriteInstance {},
	lifeLine: class extends self.ISpriteInstance {},
	oceanball: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	purpleball: class extends self.ISpriteInstance {},
	rope: class extends self.ISpriteInstance {},
	rope2: class extends self.ISpriteInstance {},
	sight: class extends self.ISpriteInstance {},
	blink: class extends self.ISpriteInstance {},
	effectStart: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	startbutton: class extends self.ISpriteInstance {},
	boardOver: class extends self.ISpriteInstance {},
	homeButton: class extends self.ISpriteInstance {},
	playButton: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Timeline: class extends self.IInstance {},
	level: class extends self.ITextInstance {},
	levelNext: class extends self.ITextInstance {},
	textLevel: class extends self.ITextInstance {},
	textLifeLine: class extends self.ITextInstance {},
	textCompleted: class extends self.ITextInstance {},
	Score: class extends self.ITextInstance {},
	textMaximum: class extends self.ITextInstance {},
	tBestScore: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	www: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	home: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Balls: class extends self.ISpriteInstance {},
	OverObject: class extends self.ISpriteInstance {},
	OverText: class extends self.ITextInstance {}
}