const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Tilemap,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.AJAX,
		C3.Plugins.NinePatch,
		C3.Plugins.Date,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.GM_SDK,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Tilemap.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerAngle,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Cnds.OnFadeEnded,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData
	];
};
self.C3_JsPropNameTable = [
	{beh_tween: 0},
	{spr_player_collision: 0},
	{map_wall: 0},
	{beh_timer: 0},
	{spr_game_manager: 0},
	{plu_keyboard: 0},
	{arr_list_of_movement: 0},
	{plu_browser: 0},
	{beh_scroll_to: 0},
	{spr_camera: 0},
	{var_context_name: 0},
	{fon_text: 0},
	{spr_arrow_conteiner: 0},
	{var_index: 0},
	{spr_arrow: 0},
	{plu_local_storage: 0},
	{spr_spike: 0},
	{bac_header_background: 0},
	{var_level: 0},
	{spr_level_number: 0},
	{beh_pin: 0},
	{spr_player_graphic: 0},
	{var_id: 0},
	{spr_key: 0},
	{spr_door: 0},
	{plu_ajax: 0},
	{spr_fade: 0},
	{spr_potion: 0},
	{arr_player_profile: 0},
	{pat_timer: 0},
	{plu_date: 0},
	{spr_smoke: 0},
	{plu_audio: 0},
	{map_ground: 0},
	{Sine: 0},
	{Sprite: 0},
	{GameMonetizeSDK: 0},
	{Touch: 0},
	{fam_synced_object: 0},
	{var_world_angle: 0},
	{var_tile_size: 0},
	{var_rotation_time: 0},
	{var_turn_duration: 0},
	{var_initial_delay: 0},
	{var_move: 0},
	{var_tutorial_step: 0},
	{var_desired_angle: 0},
	{var_key_id: 0},
	{var_selected_level_buffer: 0},
	{var_selected_level: 0},
	{var_value: 0},
	{gdcount: 0}
];

self.InstanceType = {
	spr_player_collision: class extends self.ISpriteInstance {},
	map_wall: class extends self.ITilemapInstance {},
	spr_game_manager: class extends self.ISpriteInstance {},
	plu_keyboard: class extends self.IInstance {},
	arr_list_of_movement: class extends self.IArrayInstance {},
	plu_browser: class extends self.IInstance {},
	spr_camera: class extends self.ISpriteInstance {},
	fon_text: class extends self.ISpriteFontInstance {},
	spr_arrow_conteiner: class extends self.ISpriteInstance {},
	spr_arrow: class extends self.ISpriteInstance {},
	plu_local_storage: class extends self.IInstance {},
	spr_spike: class extends self.ISpriteInstance {},
	bac_header_background: class extends self.ITiledBackgroundInstance {},
	spr_level_number: class extends self.ISpriteInstance {},
	spr_player_graphic: class extends self.ISpriteInstance {},
	spr_key: class extends self.ISpriteInstance {},
	spr_door: class extends self.ISpriteInstance {},
	plu_ajax: class extends self.IInstance {},
	spr_fade: class extends self.ISpriteInstance {},
	spr_potion: class extends self.ISpriteInstance {},
	arr_player_profile: class extends self.IArrayInstance {},
	pat_timer: class extends self.IWorldInstance {},
	plu_date: class extends self.IInstance {},
	spr_smoke: class extends self.ISpriteInstance {},
	plu_audio: class extends self.IInstance {},
	map_ground: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	fam_synced_object: class extends self.ISpriteInstance {}
}