const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Behaviors.Physics.Acts.SetAngularDamping,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Play: 0},
	{Var: 0},
	{Solid: 0},
	{Physics: 0},
	{Side_Bar: 0},
	{Laser: 0},
	{Go: 0},
	{WallCollision: 0},
	{Xposition: 0},
	{DragDrop: 0},
	{Bullet: 0},
	{Ball: 0},
	{Touch: 0},
	{Arrow: 0},
	{Axe_Ball: 0},
	{Text: 0},
	{Replay: 0},
	{BG1: 0},
	{BG2: 0},
	{Rotate: 0},
	{Sine: 0},
	{Saw: 0},
	{Cobweb: 0},
	{LaserMachine: 0},
	{SpriteFont: 0},
	{Sine2: 0},
	{Saw2: 0},
	{Bar1_cntrl: 0},
	{Home: 0},
	{Levels: 0},
	{Title: 0},
	{L: 0},
	{LocalStorage: 0},
	{Cam: 0},
	{Dog: 0},
	{Audio: 0},
	{Tween: 0},
	{Hand: 0},
	{SlideBG: 0},
	{Music: 0},
	{Slidebar: 0},
	{Slidebutton: 0},
	{Particle: 0},
	{Particles: 0},
	{splash: 0},
	{Smoke: 0},
	{www: 0},
	{more: 0},
	{Browser: 0},
	{ads: 0},
	{GameMonetizeSDK: 0},
	{Obstacles: 0},
	{BGs: 0},
	{Ball_Distance: 0},
	{End: 0},
	{LEVEL: 0},
	{LevelSave: 0},
	{PrevSpeed: 0},
	{dSpeed: 0},
	{dangle: 0},
	{Slide_Touch: 0},
	{inter: 0}
];

self.InstanceType = {
	Play: class extends self.ISpriteInstance {},
	Side_Bar: class extends self.ITiledBackgroundInstance {},
	Laser: class extends self.ITiledBackgroundInstance {},
	Ball: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Axe_Ball: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Replay: class extends self.ISpriteInstance {},
	BG1: class extends self.ITiledBackgroundInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	WallCollision: class extends self.ITextInstance {},
	Saw: class extends self.ISpriteInstance {},
	Cobweb: class extends self.ISpriteInstance {},
	LaserMachine: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Saw2: class extends self.ISpriteInstance {},
	Bar1_cntrl: class extends self.ISpriteInstance {},
	Home: class extends self.ISpriteInstance {},
	Levels: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	L: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Cam: class extends self.ISpriteInstance {},
	Dog: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Hand: class extends self.ISpriteInstance {},
	SlideBG: class extends self.ITiledBackgroundInstance {},
	Music: class extends self.ISpriteInstance {},
	Slidebar: class extends self.ISpriteInstance {},
	Slidebutton: class extends self.ISpriteInstance {},
	Particle: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	splash: class extends self.ISpriteInstance {},
	Smoke: class extends self.ISpriteInstance {},
	www: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	ads: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Obstacles: class extends self.ISpriteInstance {},
	BGs: class extends self.ITiledBackgroundInstance {}
}