{
	"version":"LAYASCENE3D:02",
	"data":{
		"type":"Scene3D",
		"props":{
			"name":"GameScene",
			"ambientColor":[
				0.212,
				0.227,
				0.259
			],
			"lightmaps":[],
			"enableFog":false,
			"fogStart":0,
			"fogRange":300,
			"fogColor":[
				0.5,
				0.5,
				0.5
			]
		},
		"child":[
			{
				"type":"Camera",
				"instanceID":0,
				"props":{
					"name":"Main Camera",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						49.36,
						-9.55
					],
					"rotation":[
						0,
						0.8191521,
						0.5735764,
						0
					],
					"scale":[
						1,
						1,
						1
					],
					"clearFlag":0,
					"orthographic":false,
					"orthographicVerticalSize":50,
					"fieldOfView":60,
					"enableHDR":false,
					"nearPlane":0.3,
					"farPlane":1000,
					"viewport":[
						0,
						0,
						1,
						1
					],
					"clearColor":[
						0.8117648,
						0.8470589,
						0.8627452,
						1
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"DirectionLight",
				"instanceID":1,
				"props":{
					"name":"Directional Light",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						3,
						2
					],
					"rotation":[
						0.1234977,
						0.8488722,
						0.4608999,
						-0.2274546
					],
					"scale":[
						1,
						1,
						1
					],
					"intensity":1,
					"lightmapBakedType":0,
					"color":[
						1,
						0.9568627,
						0.8392157
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"Sprite3D",
				"instanceID":2,
				"props":{
					"name":"_Env",
					"active":true,
					"isStatic":true,
					"layer":0,
					"position":[
						0,
						0,
						0
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						1,
						1,
						1
					]
				},
				"components":[],
				"child":[
					{
						"type":"MeshSprite3D",
						"instanceID":3,
						"props":{
							"name":"Plane",
							"active":true,
							"isStatic":true,
							"layer":0,
							"position":[
								0,
								-0.5,
								0
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								170,
								1,
								170
							],
							"meshPath":"Library/unity default resources-Cube.lm",
							"enableRender":true,
							"materials":[
								{
									"path":"Assets/Env/Module/Materials/Ground_01.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"Sprite3D",
						"instanceID":4,
						"props":{
							"name":"Trees",
							"active":true,
							"isStatic":true,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1,
								1,
								1
							]
						},
						"components":[],
						"child":[
							{
								"type":"MeshSprite3D",
								"instanceID":5,
								"props":{
									"name":"PineTree1",
									"active":true,
									"isStatic":true,
									"layer":0,
									"position":[
										-5.6,
										0,
										26.6
									],
									"rotation":[
										-2.185569E-08,
										0,
										0,
										-1
									],
									"scale":[
										7,
										7,
										7
									],
									"meshPath":"Assets/Env/Tree/PineTree-PineTree.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/Env/Tree/Materials/Pine_Leaves.lmat"
										},
										{
											"path":"Assets/Env/Tree/Materials/Pine_Trunk.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							},
							{
								"type":"MeshSprite3D",
								"instanceID":6,
								"props":{
									"name":"PineTree1 (1)",
									"active":true,
									"isStatic":true,
									"layer":0,
									"position":[
										-12.4,
										0,
										41.8
									],
									"rotation":[
										-2.185569E-08,
										0,
										0,
										-1
									],
									"scale":[
										6,
										6,
										6
									],
									"meshPath":"Assets/Env/Tree/PineTree-PineTree.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/Env/Tree/Materials/Pine_Leaves.lmat"
										},
										{
											"path":"Assets/Env/Tree/Materials/Pine_Trunk.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							},
							{
								"type":"MeshSprite3D",
								"instanceID":7,
								"props":{
									"name":"PineTree1 (2)",
									"active":true,
									"isStatic":true,
									"layer":0,
									"position":[
										10.8,
										0,
										34.9
									],
									"rotation":[
										-2.185569E-08,
										0,
										0,
										-1
									],
									"scale":[
										7,
										7,
										7
									],
									"meshPath":"Assets/Env/Tree/PineTree-PineTree.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/Env/Tree/Materials/Pine_Leaves.lmat"
										},
										{
											"path":"Assets/Env/Tree/Materials/Pine_Trunk.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							},
							{
								"type":"MeshSprite3D",
								"instanceID":8,
								"props":{
									"name":"PineTree1 (3)",
									"active":true,
									"isStatic":true,
									"layer":0,
									"position":[
										13.2,
										0,
										26.5
									],
									"rotation":[
										-2.185569E-08,
										0,
										0,
										-1
									],
									"scale":[
										5,
										5,
										5
									],
									"meshPath":"Assets/Env/Tree/PineTree-PineTree.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/Env/Tree/Materials/Pine_Leaves.lmat"
										},
										{
											"path":"Assets/Env/Tree/Materials/Pine_Trunk.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							}
						]
					},
					{
						"type":"Sprite3D",
						"instanceID":9,
						"props":{
							"name":"Rocks",
							"active":true,
							"isStatic":true,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1,
								1,
								1
							]
						},
						"components":[],
						"child":[
							{
								"type":"MeshSprite3D",
								"instanceID":10,
								"props":{
									"name":"Rock_03",
									"active":true,
									"isStatic":true,
									"layer":0,
									"position":[
										-17.4,
										2.81,
										19.93
									],
									"rotation":[
										0,
										-0.6087614,
										0,
										-0.7933534
									],
									"scale":[
										3,
										3,
										3
									],
									"meshPath":"Assets/Env/Rock/Rock_03-Icosphere.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/Env/Rock/Materials/MatRack.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							},
							{
								"type":"MeshSprite3D",
								"instanceID":11,
								"props":{
									"name":"Rock_01",
									"active":true,
									"isStatic":true,
									"layer":0,
									"position":[
										5.8,
										-0.36,
										26.6
									],
									"rotation":[
										0,
										-0.7071068,
										0,
										-0.7071068
									],
									"scale":[
										4.5,
										4.5,
										4.5
									],
									"meshPath":"Assets/Env/Rock/Rock_01-LowPolyRock.001.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/Env/Rock/Materials/MatRack.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							},
							{
								"type":"MeshSprite3D",
								"instanceID":12,
								"props":{
									"name":"Rock_04",
									"active":true,
									"isStatic":true,
									"layer":0,
									"position":[
										-14.14,
										-1.1,
										37.9
									],
									"rotation":[
										-0.6197361,
										-0.636675,
										0.3663008,
										-0.2763982
									],
									"scale":[
										3,
										3,
										3
									],
									"meshPath":"Assets/Env/Rock/Rock_04-Cube.003.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/Env/Rock/Materials/MatRack.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							}
						]
					}
				]
			},
			{
				"type":"Sprite3D",
				"instanceID":13,
				"props":{
					"name":"Path",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						0,
						0
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						1,
						1,
						1
					]
				},
				"components":[],
				"child":[]
			}
		]
	}
}