const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Behaviors.scrollto,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Exps.ImagePointCount,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Cnds.OnBackButton,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.SetLayerForceOwnTexture,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Audio.Acts.SetMuted
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{Asset: 0},
	{GLASS: 0},
	{N: 0},
	{corn: 0},
	{waterColor: 0},
	{sounds: 0},
	{music: 0},
	{cup: 0},
	{Touch: 0},
	{TiledBackground: 0},
	{Fade: 0},
	{dark: 0},
	{home: 0},
	{replay: 0},
	{start_levelsheet: 0},
	{Fill_cup_continue: 0},
	{Pin: 0},
	{full: 0},
	{levels_text: 0},
	{G_collision: 0},
	{TiledBackground2: 0},
	{Keyboard: 0},
	{open: 0},
	{level_icon: 0},
	{level_N: 0},
	{ScrollTo: 0},
	{CAM: 0},
	{hidden_bar: 0},
	{Tittle: 0},
	{Fill_cup_levels: 0},
	{var: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{inter_text: 0},
	{color_select: 0},
	{Asset2: 0},
	{Tween: 0},
	{colors: 0},
	{Particles: 0},
	{Particles2: 0},
	{CHOOSECOLOR: 0},
	{face: 0},
	{audio: 0},
	{On: 0},
	{Music: 0},
	{Fichier3: 0},
	{settings: 0},
	{bg: 0},
	{bgm: 0},
	{Rotate: 0},
	{chs: 0},
	{lv_btn: 0},
	{GameMonetizeSDK: 0},
	{Countdown: 0},
	{WATER: 0},
	{WATER2: 0},
	{WATER_ON: 0},
	{water_spilling: 0},
	{Opened_levels: 0},
	{LEVEL: 0},
	{touch_start: 0},
	{touch_in: 0},
	{touch_end: 0},
	{color: 0},
	{MUSIC: 0},
	{SOUNDS: 0}
];

self.InstanceType = {
	Asset: class extends self.ISpriteInstance {},
	GLASS: class extends self.ISpriteInstance {},
	corn: class extends self.ISpriteInstance {},
	cup: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	dark: class extends self.ITiledBackgroundInstance {},
	home: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	start_levelsheet: class extends self.ISpriteInstance {},
	Fill_cup_continue: class extends self.ISpriteInstance {},
	full: class extends self.ISpriteInstance {},
	levels_text: class extends self.ITextInstance {},
	G_collision: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	level_icon: class extends self.ISpriteInstance {},
	level_N: class extends self.ISpriteFontInstance {},
	CAM: class extends self.ISpriteInstance {},
	hidden_bar: class extends self.ITiledBackgroundInstance {},
	Tittle: class extends self.ISpriteInstance {},
	Fill_cup_levels: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	inter_text: class extends self.ITextInstance {},
	color_select: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	colors: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	CHOOSECOLOR: class extends self.ISpriteInstance {},
	face: class extends self.ISpriteInstance {},
	On: class extends self.ISpriteInstance {},
	Music: class extends self.ISpriteInstance {},
	sounds: class extends self.ISpriteInstance {},
	Fichier3: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	bgm: class extends self.ISpriteInstance {},
	chs: class extends self.ISpriteInstance {},
	lv_btn: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}