const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Persist,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.ScriptsInEvents.Common_Event27_Act1,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Particles.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Exps.X,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Particles.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Text.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{Array: 0},
	{selfW: 0},
	{selfH: 0},
	{btn_back: 0},
	{Tween: 0},
	{btn_close: 0},
	{level: 0},
	{action: 0},
	{Pin: 0},
	{btn_default: 0},
	{btn_more: 0},
	{btn_next: 0},
	{btn_play: 0},
	{btn_retry: 0},
	{btn_rew: 0},
	{btn_sound: 0},
	{btn_full_screen: 0},
	{btn_hint: 0},
	{btn_morehint: 0},
	{btn_more_main: 0},
	{bg_menu: 0},
	{Sine: 0},
	{logo: 0},
	{logo2: 0},
	{Sine2: 0},
	{flare: 0},
	{Persist: 0},
	{FireSparkParticlesMenu: 0},
	{camera: 0},
	{ScrollTo: 0},
	{camera_lerp: 0},
	{txt_menu: 0},
	{DragDrop: 0},
	{level_select_line: 0},
	{levels: 0},
	{txt_level: 0},
	{end_scroll: 0},
	{txt_label: 0},
	{firefly: 0},
	{side: 0},
	{diff_frame: 0},
	{diff: 0},
	{bg_game: 0},
	{diff_number: 0},
	{Rotate: 0},
	{circle_diff: 0},
	{icon_found: 0},
	{timer_bg: 0},
	{timerbar: 0},
	{timerbar_bg_frame: 0},
	{bg_tile2: 0},
	{bg_tile1: 0},
	{icon_heart: 0},
	{Fade: 0},
	{icon_error: 0},
	{FireSparkParticlesHeart: 0},
	{FireSparkParticlesFound: 0},
	{Bullet: 0},
	{found_light_effect: 0},
	{txt_feedback: 0},
	{swipe: 0},
	{FireSparkParticlesLevel: 0},
	{number_star: 0},
	{icon_face: 0},
	{number: 0},
	{star_burst: 0},
	{icon_lock: 0},
	{icon_hud: 0},
	{star_burst_hud: 0},
	{modal: 0},
	{background_modal: 0},
	{txt_modal: 0},
	{txt_more: 0},
	{ch1: 0},
	{ConfettiWinParticle: 0},
	{Confetti: 0},
	{bg_rew: 0},
	{bginfo: 0},
	{txt_norew: 0},
	{ch0: 0},
	{clouds: 0},
	{Timer: 0},
	{hint_star_burst: 0},
	{hint_high_light: 0},
	{Grass1: 0},
	{Grass2: 0},
	{GameMonetizeSDK: 0},
	{logo3: 0},
	{hud_buttons: 0},
	{LSSound: 0},
	{LSLevelName_Sprunki: 0},
	{currentLevel: 0},
	{playableLevel: 0},
	{isLoadedData: 0},
	{numberLevels: 0},
	{duration: 0},
	{levelsGap: 0},
	{isDrag: 0},
	{dragLastX: 0},
	{totalStars: 0},
	{maxTimer: 0},
	{timerCount: 0},
	{startGame: 0},
	{lives: 0},
	{found: 0},
	{levelStar: 0},
	{unlockNumberLevel: 0},
	{x: 0},
	{y: 0},
	{w: 0},
	{h: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	btn_back: class extends self.ISpriteInstance {},
	btn_close: class extends self.ISpriteInstance {},
	btn_default: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	btn_next: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_retry: class extends self.ISpriteInstance {},
	btn_rew: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_full_screen: class extends self.ISpriteInstance {},
	btn_hint: class extends self.ISpriteInstance {},
	btn_morehint: class extends self.ISpriteInstance {},
	btn_more_main: class extends self.ISpriteInstance {},
	bg_menu: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	logo2: class extends self.ISpriteInstance {},
	flare: class extends self.ISpriteInstance {},
	FireSparkParticlesMenu: class extends self.IParticlesInstance {},
	camera: class extends self.ISpriteInstance {},
	camera_lerp: class extends self.ISpriteInstance {},
	txt_menu: class extends self.ITextInstance {},
	level_select_line: class extends self.ITiledBackgroundInstance {},
	levels: class extends self.ISpriteInstance {},
	txt_level: class extends self.ITextInstance {},
	end_scroll: class extends self.ISpriteInstance {},
	txt_label: class extends self.ITextInstance {},
	firefly: class extends self.ISpriteInstance {},
	diff_frame: class extends self.ISpriteInstance {},
	diff: class extends self.ISpriteInstance {},
	bg_game: class extends self.ISpriteInstance {},
	circle_diff: class extends self.ISpriteInstance {},
	icon_found: class extends self.ISpriteInstance {},
	timer_bg: class extends self.ISpriteInstance {},
	timerbar: class extends self.ITiledBackgroundInstance {},
	timerbar_bg_frame: class extends self.ITiledBackgroundInstance {},
	bg_tile2: class extends self.ISpriteInstance {},
	bg_tile1: class extends self.ISpriteInstance {},
	icon_heart: class extends self.ISpriteInstance {},
	icon_error: class extends self.ISpriteInstance {},
	FireSparkParticlesHeart: class extends self.IParticlesInstance {},
	FireSparkParticlesFound: class extends self.IParticlesInstance {},
	found_light_effect: class extends self.ISpriteInstance {},
	txt_feedback: class extends self.ITextInstance {},
	swipe: class extends self.ISpriteInstance {},
	FireSparkParticlesLevel: class extends self.IParticlesInstance {},
	icon_face: class extends self.ISpriteInstance {},
	star_burst: class extends self.ISpriteInstance {},
	icon_lock: class extends self.ISpriteInstance {},
	icon_hud: class extends self.ISpriteInstance {},
	star_burst_hud: class extends self.ISpriteInstance {},
	modal: class extends self.ISpriteInstance {},
	background_modal: class extends self.ITiledBackgroundInstance {},
	txt_modal: class extends self.ITextInstance {},
	txt_more: class extends self.ITextInstance {},
	ch1: class extends self.ISpriteInstance {},
	ConfettiWinParticle: class extends self.IParticlesInstance {},
	Confetti: class extends self.ISpriteInstance {},
	bg_rew: class extends self.ISpriteInstance {},
	bginfo: class extends self.ISpriteInstance {},
	txt_norew: class extends self.ITextInstance {},
	ch0: class extends self.ISpriteInstance {},
	clouds: class extends self.ISpriteInstance {},
	hint_star_burst: class extends self.ISpriteInstance {},
	hint_high_light: class extends self.IParticlesInstance {},
	Grass1: class extends self.ISpriteInstance {},
	Grass2: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	logo3: class extends self.ISpriteInstance {},
	hud_buttons: class extends self.ISpriteInstance {}
}