const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Flikes_EasyVariable,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Flikes_EasyVariable.Exps.GetVariable,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Acts.SetCharacterSpacing,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Flikes_EasyVariable.Acts.Insert_Var,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{aAnswer: 0},
	{aFrame: 0},
	{Audio: 0},
	{Browser: 0},
	{EasyVariable: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{Mouse: 0},
	{frameNum: 0},
	{active: 0},
	{scales: 0},
	{Tween: 0},
	{sCart: 0},
	{level: 0},
	{num: 0},
	{parsCount: 0},
	{sLevel: 0},
	{sMenu: 0},
	{mod: 0},
	{sMod: 0},
	{sMusic: 0},
	{sPause: 0},
	{sSound: 0},
	{sStart: 0},
	{Sine: 0},
	{sAD: 0},
	{sInstruction: 0},
	{sSettings: 0},
	{sBack: 0},
	{Particles: 0},
	{sBG: 0},
	{sMonster: 0},
	{sOver: 0},
	{sPauseMenu: 0},
	{sRespawn: 0},
	{sRezalt: 0},
	{sWin: 0},
	{sSprite: 0},
	{sChain: 0},
	{name: 0},
	{"9patch": 0},
	{sComents: 0},
	{sLock: 0},
	{TiledBackground: 0},
	{tScore: 0},
	{texts: 0},
	{SpriteFont: 0},
	{Flikes: 0},
	{bClose: 0},
	{sCursor: 0},
	{sLogo: 0},
	{btn_more: 0},
	{btn_m_in: 0},
	{Fade: 0},
	{Nkg: 0},
	{number: 0},
	{Rotate: 0},
	{Pin: 0},
	{Timer: 0},
	{star_burst: 0},
	{ch5: 0},
	{ch2: 0},
	{GameMonetizeSDK: 0},
	{Button: 0},
	{musicName: 0},
	{soundName: 0},
	{totalCount: 0},
	{UID: 0},
	{sx: 0},
	{sy: 0},
	{x1: 0},
	{x2: 0},
	{y1: 0},
	{y2: 0},
	{UID1: 0},
	{UID2: 0},
	{sound: 0},
	{music: 0},
	{MOD: 0},
	{touchCount: 0},
	{gameStart: 0},
	{rightAnswer: 0},
	{stepMax: 0},
	{partsCount: 0},
	{openMod: 0},
	{openLevel: 0},
	{loadFinish: 0},
	{openCount1: 0},
	{openCount2: 0},
	{openCount3: 0},
	{answer1: 0},
	{answer2: 0},
	{UIDcart1: 0},
	{UIDcart2: 0},
	{coments: 0}
];

self.InstanceType = {
	aAnswer: class extends self.IArrayInstance {},
	aFrame: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	EasyVariable: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	sCart: class extends self.ISpriteInstance {},
	sLevel: class extends self.ISpriteInstance {},
	sMenu: class extends self.ISpriteInstance {},
	sMod: class extends self.ISpriteInstance {},
	sMusic: class extends self.ISpriteInstance {},
	sPause: class extends self.ISpriteInstance {},
	sSound: class extends self.ISpriteInstance {},
	sStart: class extends self.ISpriteInstance {},
	sAD: class extends self.ISpriteInstance {},
	sInstruction: class extends self.ISpriteInstance {},
	sSettings: class extends self.ISpriteInstance {},
	sBack: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	sBG: class extends self.ISpriteInstance {},
	sMonster: class extends self.ISpriteInstance {},
	sOver: class extends self.ISpriteInstance {},
	sPauseMenu: class extends self.ISpriteInstance {},
	sRespawn: class extends self.ISpriteInstance {},
	sRezalt: class extends self.ISpriteInstance {},
	sWin: class extends self.ISpriteInstance {},
	sSprite: class extends self.ISpriteInstance {},
	sChain: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	sComents: class extends self.ISpriteInstance {},
	sLock: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	tScore: class extends self.ITextInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Flikes: class extends self.ISpriteInstance {},
	bClose: class extends self.ISpriteInstance {},
	sCursor: class extends self.ISpriteInstance {},
	sLogo: class extends self.ISpriteInstance {},
	btn_more: class extends self.ISpriteInstance {},
	btn_m_in: class extends self.ISpriteInstance {},
	Nkg: class extends self.ISpriteInstance {},
	star_burst: class extends self.ISpriteInstance {},
	ch5: class extends self.ISpriteInstance {},
	ch2: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Button: class extends self.ISpriteInstance {}
}