const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Plugins.LocalStorage,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{ID_Name: 0},
	{ID_Number: 0},
	{Selected: 0},
	{Tween: 0},
	{Card: 0},
	{Touch: 0},
	{bg_cards: 0},
	{bg: 0},
	{efx_card_start_P: 0},
	{Fade: 0},
	{efx_card_d1: 0},
	{efx_card_d2: 0},
	{efx_touch: 0},
	{efx_touch2: 0},
	{txt_points_p1: 0},
	{txt_points: 0},
	{txt_points_p2: 0},
	{Mouse: 0},
	{preSelection: 0},
	{btn_p1xp2: 0},
	{avatar_p1: 0},
	{avatar_p2: 0},
	{turnAvatar: 0},
	{txt_player_info: 0},
	{Cronômetro: 0},
	{txt_timer_number: 0},
	{txt_timer: 0},
	{PopUp: 0},
	{bg_black: 0},
	{BtnNext: 0},
	{BtnRestart: 0},
	{BtnLevels: 0},
	{btn_solo: 0},
	{btn_solo_lvl: 0},
	{SineS: 0},
	{SineS2: 0},
	{SineAngle: 0},
	{logo: 0},
	{BtnAudio: 0},
	{fade: 0},
	{LocalStorege: 0},
	{Keyboard: 0},
	{BtnPause: 0},
	{txt_pause: 0},
	{Audio: 0},
	{btn_clearlvl: 0},
	{Web: 0},
	{txt_rotation: 0},
	{btn_more: 0},
	{Sine: 0},
	{btn_m2: 0},
	{Y8: 0},
	{bg_main: 0},
	{ch0: 0},
	{ch2: 0},
	{ch1: 0},
	{ch3: 0},
	{Particles: 0},
	{GameMonetizeSDK: 0},
	{f_btns: 0},
	{Timer: 0},
	{Card_1: 0},
	{Card_2: 0},
	{QuantityCard: 0},
	{CurrentCard: 0},
	{Points_P1: 0},
	{Points_P2: 0},
	{PlayerTurn: 0},
	{GameMode: 0},
	{Pause: 0},
	{OpacityWin: 0},
	{OpacityLose: 0},
	{Level_Unlocked: 0}
];

self.InstanceType = {
	Card: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	bg_cards: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	efx_card_start_P: class extends self.IParticlesInstance {},
	efx_card_d1: class extends self.ISpriteInstance {},
	efx_card_d2: class extends self.ISpriteInstance {},
	efx_touch: class extends self.ISpriteInstance {},
	efx_touch2: class extends self.ISpriteInstance {},
	txt_points_p1: class extends self.ITextInstance {},
	txt_points: class extends self.ITextInstance {},
	txt_points_p2: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	preSelection: class extends self.ISpriteInstance {},
	btn_p1xp2: class extends self.ISpriteInstance {},
	avatar_p1: class extends self.ISpriteInstance {},
	avatar_p2: class extends self.ISpriteInstance {},
	turnAvatar: class extends self.ISpriteInstance {},
	txt_player_info: class extends self.ITextInstance {},
	txt_timer_number: class extends self.ITextInstance {},
	txt_timer: class extends self.ITextInstance {},
	PopUp: class extends self.ISpriteInstance {},
	bg_black: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnLevels: class extends self.ISpriteInstance {},
	btn_solo: class extends self.ISpriteInstance {},
	btn_solo_lvl: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	BtnAudio: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	LocalStorege: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	txt_pause: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	btn_clearlvl: class extends self.ISpriteInstance {},
	Web: class extends self.IInstance {},
	txt_rotation: class extends self.ITextInstance {},
	btn_more: class extends self.ISpriteInstance {},
	btn_m2: class extends self.ISpriteInstance {},
	Y8: class extends self.ISpriteInstance {},
	bg_main: class extends self.ISpriteInstance {},
	ch0: class extends self.ISpriteInstance {},
	ch2: class extends self.ISpriteInstance {},
	ch1: class extends self.ISpriteInstance {},
	ch3: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	f_btns: class extends self.ISpriteInstance {}
}