const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Behaviors.MoveTo,
		C3.Plugins.GM_SDK,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.JavaScriptInEvents.Mainmenu_es_Event8_Act2,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Exps.Text,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Cnds.OnHitSolid,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Level_es_Event22_Act1,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Level_es_Event23_Act1,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.Audio.Acts.SetVolume
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{sound_btn: 0},
	{game_bg: 0},
	{home_btn: 0},
	{Tween: 0},
	{restart_btn: 0},
	{Play_btn: 0},
	{title: 0},
	{back_level_menu: 0},
	{level_icon_index: 0},
	{Level_Icon: 0},
	{Level_Number_Text: 0},
	{level_text_design: 0},
	{levelSelectionBlurAsset: 0},
	{levelWork: 0},
	{next_level_menu: 0},
	{Solid: 0},
	{border: 0},
	{checker: 0},
	{fish_dir: 0},
	{MoveTo: 0},
	{fish: 0},
	{grid_bg: 0},
	{shark: 0},
	{timer_progress_fg: 0},
	{next_level_btn: 0},
	{level_complete_text: 0},
	{win_lose_fish: 0},
	{level_lose_text: 0},
	{win_lose_shark: 0},
	{win_lose_transparent_bg: 0},
	{GameMonetizeSDK: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{CustomSpriteFont: 0},
	{timer_for_this_level: 0},
	{Particles: 0},
	{confetti_obj: 0},
	{most_level: 0},
	{levelmenu_index: 0},
	{most_level_menu_index: 0},
	{most_level_created: 0},
	{midshiftx: 0},
	{midshifty: 0},
	{current_level_index: 0},
	{timer_sec: 0},
	{isPlaying: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	sound_btn: class extends self.ISpriteInstance {},
	game_bg: class extends self.ISpriteInstance {},
	home_btn: class extends self.ISpriteInstance {},
	restart_btn: class extends self.ISpriteInstance {},
	Play_btn: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	back_level_menu: class extends self.ISpriteInstance {},
	Level_Icon: class extends self.ISpriteInstance {},
	Level_Number_Text: class extends self.ITextInstance {},
	level_text_design: class extends self.ISpriteInstance {},
	levelSelectionBlurAsset: class extends self.ISpriteInstance {},
	levelWork: class extends self.ISpriteInstance {},
	next_level_menu: class extends self.ISpriteInstance {},
	border: class extends self.ISpriteInstance {},
	checker: class extends self.ISpriteInstance {},
	fish: class extends self.ISpriteInstance {},
	grid_bg: class extends self.ISpriteInstance {},
	shark: class extends self.ISpriteInstance {},
	timer_progress_fg: class extends self.ISpriteInstance {},
	next_level_btn: class extends self.ISpriteInstance {},
	level_complete_text: class extends self.ISpriteInstance {},
	win_lose_fish: class extends self.ISpriteInstance {},
	level_lose_text: class extends self.ISpriteInstance {},
	win_lose_shark: class extends self.ISpriteInstance {},
	win_lose_transparent_bg: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends C3.Plugins.GM_SDK.Instance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	CustomSpriteFont: class extends self.ISpriteFontInstance {},
	timer_for_this_level: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	confetti_obj: class extends self.ISpriteInstance {}
}