const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Spritefont2.Cnds.CompareY,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{LastposX: 0},
	{LastposY: 0},
	{Firstposx: 0},
	{FirstposY: 0},
	{TruePos: 0},
	{FirstWidth: 0},
	{FirstHeight: 0},
	{img1: 0},
	{img10: 0},
	{img11: 0},
	{img12: 0},
	{img13: 0},
	{img14: 0},
	{img15: 0},
	{img16: 0},
	{img17: 0},
	{img18: 0},
	{img19: 0},
	{img2: 0},
	{img20: 0},
	{img21: 0},
	{img22: 0},
	{img23: 0},
	{img24: 0},
	{img25: 0},
	{img26: 0},
	{img27: 0},
	{img28: 0},
	{img29: 0},
	{img3: 0},
	{img30: 0},
	{img31: 0},
	{img32: 0},
	{img33: 0},
	{img34: 0},
	{img35: 0},
	{img36: 0},
	{img37: 0},
	{img38: 0},
	{img39: 0},
	{img4: 0},
	{img40: 0},
	{img41: 0},
	{img42: 0},
	{img43: 0},
	{img44: 0},
	{img45: 0},
	{img46: 0},
	{img47: 0},
	{img48: 0},
	{img49: 0},
	{img5: 0},
	{img50: 0},
	{img51: 0},
	{img52: 0},
	{img53: 0},
	{img54: 0},
	{img55: 0},
	{img56: 0},
	{img57: 0},
	{img58: 0},
	{img59: 0},
	{img6: 0},
	{img60: 0},
	{img7: 0},
	{img8: 0},
	{img9: 0},
	{BG: 0},
	{Shadow: 0},
	{Touch: 0},
	{Audio: 0},
	{Img: 0},
	{Replay: 0},
	{Home: 0},
	{Text: 0},
	{play: 0},
	{LocalStorage: 0},
	{BG1: 0},
	{Var: 0},
	{SlideBG: 0},
	{L: 0},
	{Cam: 0},
	{Slidebar: 0},
	{DragDrop: 0},
	{Slidebutton: 0},
	{Level_Numbers: 0},
	{Title: 0},
	{Levels: 0},
	{Particle1: 0},
	{Particle2: 0},
	{Particle3: 0},
	{Particle_spawn: 0},
	{Tween: 0},
	{Hand: 0},
	{Music: 0},
	{Level_Text: 0},
	{Setting: 0},
	{www: 0},
	{more: 0},
	{g8: 0},
	{Browser: 0},
	{GameMonetizeSDK: 0},
	{Images: 0},
	{UI: 0},
	{BGs: 0},
	{Particles: 0},
	{Complated: 0},
	{Save: 0},
	{PrevSpeed: 0},
	{dSpeed: 0},
	{dangle: 0},
	{Slide_Touch: 0},
	{AdTimer: 0},
	{Inter: 0}
];

self.InstanceType = {
	img1: class extends self.ISpriteInstance {},
	img10: class extends self.ISpriteInstance {},
	img11: class extends self.ISpriteInstance {},
	img12: class extends self.ISpriteInstance {},
	img13: class extends self.ISpriteInstance {},
	img14: class extends self.ISpriteInstance {},
	img15: class extends self.ISpriteInstance {},
	img16: class extends self.ISpriteInstance {},
	img17: class extends self.ISpriteInstance {},
	img18: class extends self.ISpriteInstance {},
	img19: class extends self.ISpriteInstance {},
	img2: class extends self.ISpriteInstance {},
	img20: class extends self.ISpriteInstance {},
	img21: class extends self.ISpriteInstance {},
	img22: class extends self.ISpriteInstance {},
	img23: class extends self.ISpriteInstance {},
	img24: class extends self.ISpriteInstance {},
	img25: class extends self.ISpriteInstance {},
	img26: class extends self.ISpriteInstance {},
	img27: class extends self.ISpriteInstance {},
	img28: class extends self.ISpriteInstance {},
	img29: class extends self.ISpriteInstance {},
	img3: class extends self.ISpriteInstance {},
	img30: class extends self.ISpriteInstance {},
	img31: class extends self.ISpriteInstance {},
	img32: class extends self.ISpriteInstance {},
	img33: class extends self.ISpriteInstance {},
	img34: class extends self.ISpriteInstance {},
	img35: class extends self.ISpriteInstance {},
	img36: class extends self.ISpriteInstance {},
	img37: class extends self.ISpriteInstance {},
	img38: class extends self.ISpriteInstance {},
	img39: class extends self.ISpriteInstance {},
	img4: class extends self.ISpriteInstance {},
	img40: class extends self.ISpriteInstance {},
	img41: class extends self.ISpriteInstance {},
	img42: class extends self.ISpriteInstance {},
	img43: class extends self.ISpriteInstance {},
	img44: class extends self.ISpriteInstance {},
	img45: class extends self.ISpriteInstance {},
	img46: class extends self.ISpriteInstance {},
	img47: class extends self.ISpriteInstance {},
	img48: class extends self.ISpriteInstance {},
	img49: class extends self.ISpriteInstance {},
	img5: class extends self.ISpriteInstance {},
	img50: class extends self.ISpriteInstance {},
	img51: class extends self.ISpriteInstance {},
	img52: class extends self.ISpriteInstance {},
	img53: class extends self.ISpriteInstance {},
	img54: class extends self.ISpriteInstance {},
	img55: class extends self.ISpriteInstance {},
	img56: class extends self.ISpriteInstance {},
	img57: class extends self.ISpriteInstance {},
	img58: class extends self.ISpriteInstance {},
	img59: class extends self.ISpriteInstance {},
	img6: class extends self.ISpriteInstance {},
	img60: class extends self.ISpriteInstance {},
	img7: class extends self.ISpriteInstance {},
	img8: class extends self.ISpriteInstance {},
	img9: class extends self.ISpriteInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	Shadow: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Img: class extends self.ISpriteInstance {},
	Replay: class extends self.ISpriteInstance {},
	Home: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	play: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	BG1: class extends self.ITiledBackgroundInstance {},
	SlideBG: class extends self.ITiledBackgroundInstance {},
	L: class extends self.ISpriteInstance {},
	Cam: class extends self.ISpriteInstance {},
	Slidebar: class extends self.ISpriteInstance {},
	Slidebutton: class extends self.ISpriteInstance {},
	Level_Numbers: class extends self.ISpriteFontInstance {},
	Title: class extends self.ISpriteInstance {},
	Levels: class extends self.ISpriteInstance {},
	Particle1: class extends self.IParticlesInstance {},
	Particle2: class extends self.IParticlesInstance {},
	Particle3: class extends self.IParticlesInstance {},
	Particle_spawn: class extends self.ISpriteInstance {},
	Hand: class extends self.ISpriteInstance {},
	Music: class extends self.ISpriteInstance {},
	Level_Text: class extends self.ISpriteFontInstance {},
	Setting: class extends self.ISpriteInstance {},
	www: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	g8: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Images: class extends self.ISpriteInstance {},
	UI: class extends self.ISpriteInstance {},
	BGs: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {}
}