const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Particles,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.JavaScriptInEvents.Gamesheet_Event3_Act2,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.JavaScriptInEvents.Gamesheet_Event43_Act1,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.JavaScriptInEvents.Gamesheet_Event64_Act1,
		C3.JavaScriptInEvents.Gamesheet_Event65_Act1,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.JavaScriptInEvents.Mainmenu_es_Event9_Act2,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.EveryTick
	];
};
self.C3_JsPropNameTable = [
	{level_icon_index: 0},
	{lvl_win_ball: 0},
	{Tween: 0},
	{Level_Icon: 0},
	{Level_UI_Text: 0},
	{Level_Number_Text: 0},
	{fillup_anime_yellow2: 0},
	{fillup_anime_yellow1: 0},
	{fillup_anime_yellow3: 0},
	{fillup_anime_green: 0},
	{fillup_anime_red1: 0},
	{fillup_anime_red2: 0},
	{fillup_anime_cream: 0},
	{star_animation: 0},
	{star_animation_glass_fill: 0},
	{Bg: 0},
	{BallsCount: 0},
	{Done: 0},
	{win_bottle: 0},
	{Glass: 0},
	{Index: 0},
	{Parent: 0},
	{Ball: 0},
	{Touch: 0},
	{LevelDone_Text: 0},
	{LevelBG: 0},
	{LevelText: 0},
	{PlayButton: 0},
	{menu_BG: 0},
	{BlackBG: 0},
	{WinBall: 0},
	{rayAsset: 0},
	{Btn_Sound: 0},
	{gameTitleAsset: 0},
	{levelBgAsset: 0},
	{levelSelectionBlurAsset: 0},
	{levelsAsset: 0},
	{btn_home: 0},
	{strawAsset: 0},
	{pause_cancel: 0},
	{elementArtboard3: 0},
	{btn_restart: 0},
	{btn_pause: 0},
	{gamePlayBgAsset: 0},
	{elementArtboard2: 0},
	{btn_next_level: 0},
	{sortedTextAsset: 0},
	{winStarBigAsset: 0},
	{winStarAsset: 0},
	{level_menu_next: 0},
	{level_menu_back: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{BlackBG2: 0},
	{btn_restart2: 0},
	{StarParticles_selectedBall: 0},
	{GameMonetizeSDK: 0},
	{FBall: 0},
	{FGlass: 0},
	{Selected_Glass: 0},
	{Selected_Ball: 0},
	{current_level_index: 0},
	{pipe_bottle_x: 0},
	{win_fruit: 0},
	{rand: 0},
	{GlassTarget: 0},
	{CorrectCount: 0},
	{paused: 0},
	{most_level: 0},
	{levelmenu_index: 0},
	{most_level_menu_index: 0}
];

self.InstanceType = {
	Level_Icon: class extends self.ISpriteInstance {},
	Level_UI_Text: class extends self.ITextInstance {},
	Level_Number_Text: class extends self.ITextInstance {},
	fillup_anime_yellow2: class extends self.ISpriteInstance {},
	fillup_anime_yellow1: class extends self.ISpriteInstance {},
	fillup_anime_yellow3: class extends self.ISpriteInstance {},
	fillup_anime_green: class extends self.ISpriteInstance {},
	fillup_anime_red1: class extends self.ISpriteInstance {},
	fillup_anime_red2: class extends self.ISpriteInstance {},
	fillup_anime_cream: class extends self.ISpriteInstance {},
	star_animation: class extends self.ISpriteInstance {},
	star_animation_glass_fill: class extends self.ISpriteInstance {},
	Bg: class extends self.ISpriteInstance {},
	Glass: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LevelDone_Text: class extends self.ITextInstance {},
	LevelBG: class extends self.ISpriteInstance {},
	LevelText: class extends self.ITextInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	menu_BG: class extends self.ISpriteInstance {},
	BlackBG: class extends self.ISpriteInstance {},
	WinBall: class extends self.ISpriteInstance {},
	rayAsset: class extends self.ISpriteInstance {},
	Btn_Sound: class extends self.ISpriteInstance {},
	gameTitleAsset: class extends self.ISpriteInstance {},
	levelBgAsset: class extends self.ISpriteInstance {},
	levelSelectionBlurAsset: class extends self.ISpriteInstance {},
	levelsAsset: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	strawAsset: class extends self.ISpriteInstance {},
	pause_cancel: class extends self.ISpriteInstance {},
	elementArtboard3: class extends self.ISpriteInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	btn_pause: class extends self.ISpriteInstance {},
	gamePlayBgAsset: class extends self.ISpriteInstance {},
	elementArtboard2: class extends self.ISpriteInstance {},
	btn_next_level: class extends self.ISpriteInstance {},
	sortedTextAsset: class extends self.ISpriteInstance {},
	winStarBigAsset: class extends self.ISpriteInstance {},
	winStarAsset: class extends self.ISpriteInstance {},
	level_menu_next: class extends self.ISpriteInstance {},
	level_menu_back: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BlackBG2: class extends self.ISpriteInstance {},
	btn_restart2: class extends self.ISpriteInstance {},
	StarParticles_selectedBall: class extends self.IParticlesInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	FBall: class extends self.ISpriteInstance {},
	FGlass: class extends self.ISpriteInstance {}
}