const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.NinePatch,
		C3.Plugins.Dictionary,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Dictionary.Cnds.CompareCurrentValue,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Dictionary.Exps.CurrentValue,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Dictionary.Acts.InstanceSignal,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetAngle,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Pin.Exps.PinnedUID,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Touch.Cnds.OnTouchObject
	];
};
self.C3_JsPropNameTable = [
	{levels: 0},
	{pX: 0},
	{pY: 0},
	{pZ: 0},
	{ID: 0},
	{enabled: 0},
	{Tween: 0},
	{Pin: 0},
	{tile: 0},
	{touchArea: 0},
	{r: 0},
	{c: 0},
	{z: 0},
	{TiledBackground: 0},
	{Touch: 0},
	{Browser: 0},
	{colors: 0},
	{AJAX: 0},
	{JSON: 0},
	{sX: 0},
	{sY: 0},
	{dX: 0},
	{dY: 0},
	{active: 0},
	{connection: 0},
	{linesLists: 0},
	{BACKGROUND_GAME: 0},
	{dW: 0},
	{dH: 0},
	{TITLE_1: 0},
	{TITLE_2: 0},
	{scale: 0},
	{PLAY_BTN: 0},
	{TUTORIAL_BTN: 0},
	{menu_submenu_bg_1: 0},
	{menu_submenu_bg_2: 0},
	{lvCount: 0},
	{easy_btn: 0},
	{medium_btn: 0},
	{hard_btn: 0},
	{back_btn: 0},
	{field_bg: 0},
	{i: 0},
	{j: 0},
	{n: 0},
	{level_single: 0},
	{levelsPage: 0},
	{tutorial_complete: 0},
	{tutorial_finger: 0},
	{tutorial_title: 0},
	{easy_levelCount: 0},
	{medium_levelCount: 0},
	{hard_levelCount: 0},
	{gameData: 0},
	{LocalStorage: 0},
	{levels_header_txt: 0},
	{header_info: 0},
	{level_number: 0},
	{game_header_line: 0},
	{game_header_txt: 0},
	{home_btn: 0},
	{tutorial_txt: 0},
	{tutorial: 0},
	{difficult_lock_mask: 0},
	{difficult_lock: 0},
	{quit_bg: 0},
	{quit_box: 0},
	{quit_txt: 0},
	{quit_confirm: 0},
	{quit_cancel: 0},
	{touch_effect: 0},
	{win_bg: 0},
	{win_box: 0},
	{win_replay: 0},
	{win_next: 0},
	{win_title: 0},
	{win_txt: 0},
	{levelsCount: 0},
	{Audio: 0},
	{line: 0},
	{cover_alert_box: 0},
	{cover_alert_txt: 0},
	{cover_alert_bg: 0},
	{sound_btn: 0},
	{logo: 0},
	{Sprite: 0},
	{GameMonetizeSDK: 0},
	{level: 0},
	{singleWidth: 0},
	{singleHeight: 0},
	{width5: 0},
	{height5: 0},
	{type: 0},
	{startX: 0},
	{startY: 0},
	{centerX: 0},
	{centerY: 0},
	{curLayer: 0},
	{height: 0},
	{width: 0},
	{k: 0},
	{ix: 0},
	{curY: 0},
	{curX: 0},
	{iy: 0},
	{g: 0},
	{b: 0},
	{lv: 0},
	{line_scale: 0},
	{line_halfHeight: 0},
	{prevX: 0},
	{prevY: 0},
	{curColor: 0},
	{lastUID: 0},
	{firstTouch: 0},
	{canceled: 0},
	{onlyResume: 0},
	{breakingLine: 0},
	{firstCoverAlert: 0},
	{linked: 0},
	{canDestroy: 0},
	{can: 0},
	{tempColor: 0},
	{x: 0},
	{y: 0},
	{oY: 0},
	{oX: 0},
	{list: 0},
	{color: 0},
	{found: 0},
	{s: 0},
	{d: 0},
	{dir: 0},
	{touchColor: 0},
	{isNone: 0},
	{prvX: 0},
	{prvY: 0},
	{UID: 0},
	{tot: 0},
	{allCovered: 0},
	{tempValue: 0},
	{changeDif: 0},
	{next: 0},
	{difficult: 0},
	{difIndex: 0},
	{count: 0},
	{step: 0},
	{stepTime: 0},
	{highlight: 0},
	{pagesCount: 0},
	{waitTime: 0},
	{singleSize: 0},
	{number: 0},
	{curPage: 0},
	{music: 0}
];

self.InstanceType = {
	levels: class extends self.IArrayInstance {},
	tile: class extends self.ISpriteInstance {},
	touchArea: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	colors: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	connection: class extends self.IWorldInstance {},
	linesLists: class extends self.IDictionaryInstance {},
	BACKGROUND_GAME: class extends self.ISpriteInstance {},
	TITLE_1: class extends self.ISpriteInstance {},
	TITLE_2: class extends self.ISpriteInstance {},
	PLAY_BTN: class extends self.ISpriteInstance {},
	TUTORIAL_BTN: class extends self.ISpriteInstance {},
	menu_submenu_bg_1: class extends self.ITiledBackgroundInstance {},
	menu_submenu_bg_2: class extends self.ITiledBackgroundInstance {},
	easy_btn: class extends self.ISpriteInstance {},
	medium_btn: class extends self.ISpriteInstance {},
	hard_btn: class extends self.ISpriteInstance {},
	back_btn: class extends self.ISpriteInstance {},
	field_bg: class extends self.ISpriteInstance {},
	level_single: class extends self.ISpriteInstance {},
	levelsPage: class extends self.ISpriteInstance {},
	tutorial_complete: class extends self.ISpriteInstance {},
	tutorial_finger: class extends self.ISpriteInstance {},
	tutorial_title: class extends self.ISpriteFontInstance {},
	easy_levelCount: class extends self.ISpriteFontInstance {},
	medium_levelCount: class extends self.ISpriteFontInstance {},
	hard_levelCount: class extends self.ISpriteFontInstance {},
	gameData: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	levels_header_txt: class extends self.ISpriteFontInstance {},
	header_info: class extends self.IArrayInstance {},
	level_number: class extends self.ISpriteFontInstance {},
	game_header_line: class extends self.ITiledBackgroundInstance {},
	game_header_txt: class extends self.ISpriteFontInstance {},
	home_btn: class extends self.ISpriteInstance {},
	tutorial_txt: class extends self.ISpriteFontInstance {},
	tutorial: class extends self.IArrayInstance {},
	difficult_lock_mask: class extends self.ITiledBackgroundInstance {},
	difficult_lock: class extends self.ISpriteInstance {},
	quit_bg: class extends self.ITiledBackgroundInstance {},
	quit_box: class extends self.ISpriteInstance {},
	quit_txt: class extends self.ISpriteFontInstance {},
	quit_confirm: class extends self.ISpriteInstance {},
	quit_cancel: class extends self.ISpriteInstance {},
	touch_effect: class extends self.ISpriteInstance {},
	win_bg: class extends self.ITiledBackgroundInstance {},
	win_box: class extends self.ISpriteInstance {},
	win_replay: class extends self.ISpriteInstance {},
	win_next: class extends self.ISpriteInstance {},
	win_title: class extends self.ISpriteFontInstance {},
	win_txt: class extends self.ISpriteFontInstance {},
	levelsCount: class extends self.IDictionaryInstance {},
	Audio: class extends self.IInstance {},
	line: class extends self.ISpriteInstance {},
	cover_alert_box: class extends self.ISpriteInstance {},
	cover_alert_txt: class extends self.ISpriteFontInstance {},
	cover_alert_bg: class extends self.ITiledBackgroundInstance {},
	sound_btn: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {}
}