const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Flowchart,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Behaviors.Tween,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.Browser,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Flowchart.Cnds.HasFlowchart,
		C3.Plugins.Flowchart.Acts.StartFlowchart,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Flowchart.Acts.ResetFlowchart,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Flowchart.Exps.NodeTag,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Flowchart.Cnds.CompareNodeTag,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Flowchart.Exps.OutputValue,
		C3.Plugins.Flowchart.Acts.GotoNextFlowchartNode,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Flowchart.Cnds.CompareOutputName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{posX: 0},
	{posY: 0},
	{Square: 0},
	{Flowchart: 0},
	{absoluteY: 0},
	{WhitePiece: 0},
	{WhiteKing: 0},
	{BlackKing: 0},
	{txtMoves: 0},
	{ArrAvailablePos: 0},
	{Tween: 0},
	{AvailableMarker: 0},
	{ArrAttackPos: 0},
	{PromotePiece: 0},
	{PromoteFrame: 0},
	{txtPromote: 0},
	{Touch: 0},
	{ResetButton: 0},
	{txtEndgame: 0},
	{EndgameFrame: 0},
	{txtGLP: 0},
	{ArrLogs: 0},
	{txtTutorial: 0},
	{Fader: 0},
	{BoardSprite: 0},
	{ScrollingBG: 0},
	{Sine: 0},
	{PLAYTEXT: 0},
	{igraj: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Menu: 0},
	{menucrte: 0},
	{Audio: 0},
	{BSound: 0},
	{Menu2: 0},
	{GameMonetizeSDK: 0},
	{moregames: 0},
	{Browser: 0},
	{DragDrop: 0},
	{Pieces: 0},
	{SQOFFX: 0},
	{SQOFFY: 0},
	{SQSIZE: 0},
	{movesLeft: 0},
	{logCount: 0},
	{Sound: 0},
	{SoundEf: 0},
	{goToX: 0},
	{goToY: 0},
	{tempCount: 0},
	{rndX: 0},
	{rndY: 0},
	{message: 0},
	{attackedByPawn: 0},
	{x: 0},
	{y: 0},
	{attackedByRook: 0},
	{attackedByQueen: 0},
	{currOffset: 0},
	{attack: 0},
	{tempPosX: 0},
	{tempPosY: 0},
	{bestXY: 0},
	{bestDist: 0},
	{inList: 0},
	{containsPiece: 0}
];

self.InstanceType = {
	Square: class extends self.ISpriteInstance {},
	Flowchart: class extends self.IInstance {},
	WhitePiece: class extends self.ISpriteInstance {},
	WhiteKing: class extends self.ISpriteInstance {},
	BlackKing: class extends self.ISpriteInstance {},
	txtMoves: class extends self.ITextInstance {},
	ArrAvailablePos: class extends self.IArrayInstance {},
	AvailableMarker: class extends self.ISpriteInstance {},
	ArrAttackPos: class extends self.IArrayInstance {},
	PromotePiece: class extends self.ISpriteInstance {},
	PromoteFrame: class extends self.IWorldInstance {},
	txtPromote: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	ResetButton: class extends self.ISpriteInstance {},
	txtEndgame: class extends self.ITextInstance {},
	EndgameFrame: class extends self.IWorldInstance {},
	txtGLP: class extends self.ITextInstance {},
	ArrLogs: class extends self.IArrayInstance {},
	txtTutorial: class extends self.ITextInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	BoardSprite: class extends self.ISpriteInstance {},
	ScrollingBG: class extends self.ITiledBackgroundInstance {},
	PLAYTEXT: class extends self.ISpriteInstance {},
	igraj: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	menucrte: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	BSound: class extends self.ISpriteInstance {},
	Menu2: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	moregames: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Pieces: class extends self.ISpriteInstance {}
}