const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.Timer,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Plugins.gpx_GamePixSDK,
		C3.Plugins.GM_SDK,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Text.Exps.PickedCount,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{TITLE: 0},
	{Sine: 0},
	{Sine2: 0},
	{LUPA: 0},
	{SCENE_ITENS: 0},
	{I: 0},
	{Rotate: 0},
	{SOUND_OFF: 0},
	{PLAY_BTN: 0},
	{Touch: 0},
	{LABEL_LV: 0},
	{DOUBT: 0},
	{TINTA_BLUE: 0},
	{BOARD: 0},
	{BOARD_ITENS: 0},
	{word: 0},
	{verificado: 0},
	{OBJECTS_LVL1: 0},
	{info: 0},
	{LETTER: 0},
	{OBJECTS_ENDGAME: 0},
	{label_timer: 0},
	{label_time: 0},
	{level_inf: 0},
	{level_inf2: 0},
	{level_inf3: 0},
	{level_inf4: 0},
	{level_inf5: 0},
	{effect_into: 0},
	{line: 0},
	{line2: 0},
	{check: 0},
	{Keyboard: 0},
	{check2: 0},
	{OK: 0},
	{INFO: 0},
	{OBSTACLE: 0},
	{hour: 0},
	{min: 0},
	{sec: 0},
	{Timer: 0},
	{timer_game_current: 0},
	{LocalStorage: 0},
	{timer_end_game_best: 0},
	{ArrayCurrentTimer: 0},
	{ArrayBestTimer: 0},
	{timer_texts: 0},
	{infoNum: 0},
	{scores_game: 0},
	{ArrayBestScores: 0},
	{scores_game2: 0},
	{scores_game3: 0},
	{scores_game4: 0},
	{scores_game5: 0},
	{CLOUD: 0},
	{text_dica: 0},
	{ArrDicasLevels1: 0},
	{star: 0},
	{ativo: 0},
	{spawn_star: 0},
	{star_ui: 0},
	{ArrDicasLevels2: 0},
	{ArrDicasLevels3: 0},
	{ArrDicasLevels4: 0},
	{ArrDicasLevels5: 0},
	{ArrDicasLevels6: 0},
	{ArrDicasLevels7: 0},
	{ArrDicasLevels8: 0},
	{ArrDicasLevels9: 0},
	{ArrDicasLevels10: 0},
	{LUPA_PALAVRAS_OCULTAS: 0},
	{TEXT_WORDS_HIDDEN: 0},
	{NEW_GAME: 0},
	{CONTINUE: 0},
	{home_btn: 0},
	{next_btn: 0},
	{Audio: 0},
	{consultaHighscoreFinal: 0},
	{Fade: 0},
	{FADE_CONGRATS: 0},
	{timer_FINAL_end_game: 0},
	{INST: 0},
	{BLACK_SCREEN: 0},
	{INST2: 0},
	{INST3: 0},
	{text_calcul: 0},
	{Fade2: 0},
	{NG_STUDIO: 0},
	{GamePixSDK: 0},
	{GameMonetizeSDK: 0},
	{Tween: 0},
	{TWEEN_ITENS: 0},
	{EFFECT: 0},
	{LSNametimerlevel1: 0},
	{LSNametimerlevel2: 0},
	{LSNametimerlevel3: 0},
	{LSNametimerlevel4: 0},
	{LSNametimerlevel5: 0},
	{LsLevelGame: 0},
	{playableLevel: 0},
	{inst: 0},
	{i: 0},
	{sound: 0},
	{Length: 0},
	{Select: 0},
	{ListWord: 0},
	{level_acertos: 0},
	{currentLevel: 0},
	{Level1_timer: 0},
	{Level1_timer2: 0},
	{minu: 0},
	{hour2: 0},
	{minu2: 0},
	{sec2: 0},
	{timer: 0},
	{hightimer: 0},
	{hightimer2: 0},
	{hightimer3: 0},
	{hightimer4: 0},
	{hightimer5: 0},
	{MeuArrayLvl1: 0},
	{completeFase: 0},
	{MeuArrayBestScore: 0},
	{score: 0},
	{highScore: 0},
	{highScore2: 0},
	{highScore3: 0},
	{highScore4: 0},
	{highScore5: 0},
	{inc: 0},
	{secondsControllerDica: 0},
	{WORDS_HIDDEN: 0},
	{HighscoreFinal: 0},
	{timerFinal: 0},
	{GameOn: 0},
	{OBS: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	TITLE: class extends self.ISpriteInstance {},
	LUPA: class extends self.ISpriteInstance {},
	SCENE_ITENS: class extends self.ISpriteInstance {},
	I: class extends self.ISpriteInstance {},
	SOUND_OFF: class extends self.ISpriteInstance {},
	PLAY_BTN: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LABEL_LV: class extends self.ISpriteInstance {},
	DOUBT: class extends self.ISpriteInstance {},
	TINTA_BLUE: class extends self.ISpriteInstance {},
	BOARD: class extends self.ISpriteInstance {},
	BOARD_ITENS: class extends self.ISpriteInstance {},
	OBJECTS_LVL1: class extends self.ISpriteInstance {},
	LETTER: class extends self.ITextInstance {},
	OBJECTS_ENDGAME: class extends self.ISpriteInstance {},
	label_timer: class extends self.ISpriteInstance {},
	label_time: class extends self.ISpriteInstance {},
	level_inf: class extends self.ISpriteInstance {},
	level_inf2: class extends self.ISpriteInstance {},
	level_inf3: class extends self.ISpriteInstance {},
	level_inf4: class extends self.ISpriteInstance {},
	level_inf5: class extends self.ISpriteInstance {},
	effect_into: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	line2: class extends self.ISpriteInstance {},
	check: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	check2: class extends self.ISpriteInstance {},
	OK: class extends self.ISpriteInstance {},
	OBSTACLE: class extends self.ISpriteInstance {},
	timer_game_current: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	timer_end_game_best: class extends self.ITextInstance {},
	ArrayCurrentTimer: class extends self.IArrayInstance {},
	ArrayBestTimer: class extends self.IArrayInstance {},
	timer_texts: class extends self.ITextInstance {},
	scores_game: class extends self.ITextInstance {},
	ArrayBestScores: class extends self.IArrayInstance {},
	scores_game2: class extends self.ITextInstance {},
	scores_game3: class extends self.ITextInstance {},
	scores_game4: class extends self.ITextInstance {},
	scores_game5: class extends self.ITextInstance {},
	CLOUD: class extends self.ISpriteInstance {},
	text_dica: class extends self.ITextInstance {},
	ArrDicasLevels1: class extends self.IArrayInstance {},
	star: class extends self.ISpriteInstance {},
	spawn_star: class extends self.ISpriteInstance {},
	star_ui: class extends self.ISpriteInstance {},
	ArrDicasLevels2: class extends self.IArrayInstance {},
	ArrDicasLevels3: class extends self.IArrayInstance {},
	ArrDicasLevels4: class extends self.IArrayInstance {},
	ArrDicasLevels5: class extends self.IArrayInstance {},
	ArrDicasLevels6: class extends self.IArrayInstance {},
	ArrDicasLevels7: class extends self.IArrayInstance {},
	ArrDicasLevels8: class extends self.IArrayInstance {},
	ArrDicasLevels9: class extends self.IArrayInstance {},
	ArrDicasLevels10: class extends self.IArrayInstance {},
	LUPA_PALAVRAS_OCULTAS: class extends self.ISpriteInstance {},
	TEXT_WORDS_HIDDEN: class extends self.ITextInstance {},
	NEW_GAME: class extends self.ISpriteInstance {},
	CONTINUE: class extends self.ISpriteInstance {},
	home_btn: class extends self.ISpriteInstance {},
	next_btn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	consultaHighscoreFinal: class extends self.ISpriteInstance {},
	FADE_CONGRATS: class extends self.ISpriteInstance {},
	timer_FINAL_end_game: class extends self.ITextInstance {},
	INST: class extends self.ISpriteInstance {},
	BLACK_SCREEN: class extends self.ISpriteInstance {},
	INST2: class extends self.ISpriteInstance {},
	INST3: class extends self.ISpriteInstance {},
	text_calcul: class extends self.ITextInstance {},
	NG_STUDIO: class extends self.ISpriteInstance {},
	GamePixSDK: class extends self.IInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	TWEEN_ITENS: class extends self.ISpriteInstance {}
}