const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Behaviors.Physics,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.NinePatch,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.NinePatch.Exps.IID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.NinePatch.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.DrawingCanvas.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.NinePatch.Exps.Count,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Browser.Acts.Reload
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{BtnSettings: 0},
	{BtnRestart: 0},
	{BtnHints: 0},
	{BtnMusic: 0},
	{BtnSound: 0},
	{HintsCounter: 0},
	{LevelText: 0},
	{LevelTextPanel: 0},
	{BtnHome: 0},
	{BtnNext: 0},
	{WinEmoji: 0},
	{WinText: 0},
	{BtnMore: 0},
	{Sine: 0},
	{FailEmoji: 0},
	{FailText: 0},
	{TimesUpText: 0},
	{DashedLine: 0},
	{Paper: 0},
	{Pin: 0},
	{Ball_2: 0},
	{Ball_1: 0},
	{W_Value: 0},
	{Line: 0},
	{Physics: 0},
	{Link: 0},
	{PhysicalArea: 0},
	{TouchTrigger: 0},
	{FaceType: 0},
	{Egg: 0},
	{EyebrowsBad: 0},
	{eyes: 0},
	{direction: 0},
	{prevDirection: 0},
	{eyes2: 0},
	{EyesLine: 0},
	{MouthBad: 0},
	{EyelidsBad: 0},
	{Ground: 0},
	{Eraser: 0},
	{Texture: 0},
	{DrawingCanvas: 0},
	{Egg2: 0},
	{EyelidsGood: 0},
	{MouthGood: 0},
	{EyebrowsGood: 0},
	{SpeechBubble: 0},
	{Hint: 0},
	{Start_x: 0},
	{Start_y: 0},
	{canMove: 0},
	{MoveTo: 0},
	{Pencil: 0},
	{HintPathLine: 0},
	{Fade: 0},
	{HintCursor: 0},
	{EggExplosionSprite: 0},
	{EggSilhouette: 0},
	{spawn_x: 0},
	{spawn_y: 0},
	{P1_Image: 0},
	{P2_Image: 0},
	{Particles1: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Rotate: 0},
	{Sine2: 0},
	{Confetti: 0},
	{ConfettiParticles: 0},
	{Swing1: 0},
	{Swing2: 0},
	{SwingPoint: 0},
	{Rope: 0},
	{RopeBase: 0},
	{Stick: 0},
	{InitiallyActive: 0},
	{Wheel: 0},
	{LoadingText: 0},
	{Logo: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Background: 0},
	{Fader: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Audio: 0},
	{BtnStart: 0},
	{NoButton: 0},
	{YesButton: 0},
	{TutReset: 0},
	{Gear: 0},
	{GameMonetizeSDK: 0},
	{Family1: 0},
	{LevelResetButtons: 0},
	{isSoundActive: 0},
	{isMusicActive: 0},
	{isGameActive: 0},
	{Level: 0},
	{CanDraw: 0},
	{Drawing: 0},
	{LinkWidth: 0},
	{prevX: 0},
	{prevY: 0},
	{P_Top: 0},
	{P_Bottom: 0},
	{P_Left: 0},
	{P_Right: 0},
	{TotalLineLength: 0},
	{isTimerActive: 0},
	{Timer: 0},
	{isHintVisible: 0},
	{Hints: 0},
	{AllLevelsCount: 0},
	{IsAllDataLoaded: 0}
];

self.InstanceType = {
	BtnSettings: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnHints: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	HintsCounter: class extends self.ISpriteInstance {},
	LevelText: class extends self.ISpriteFontInstance {},
	LevelTextPanel: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	WinEmoji: class extends self.ISpriteInstance {},
	WinText: class extends self.ISpriteInstance {},
	BtnMore: class extends self.ISpriteInstance {},
	FailEmoji: class extends self.ISpriteInstance {},
	FailText: class extends self.ISpriteInstance {},
	TimesUpText: class extends self.ISpriteInstance {},
	DashedLine: class extends self.ITiledBackgroundInstance {},
	Paper: class extends self.ITiledBackgroundInstance {},
	Ball_2: class extends self.ISpriteInstance {},
	Ball_1: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Link: class extends self.ISpriteInstance {},
	PhysicalArea: class extends self.ISpriteInstance {},
	TouchTrigger: class extends self.ISpriteInstance {},
	Egg: class extends self.ISpriteInstance {},
	EyebrowsBad: class extends self.ISpriteInstance {},
	eyes: class extends self.ISpriteInstance {},
	eyes2: class extends self.ISpriteInstance {},
	EyesLine: class extends self.ISpriteInstance {},
	MouthBad: class extends self.ISpriteInstance {},
	EyelidsBad: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Eraser: class extends self.ISpriteInstance {},
	Texture: class extends self.ITiledBackgroundInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Egg2: class extends self.ISpriteInstance {},
	EyelidsGood: class extends self.ISpriteInstance {},
	MouthGood: class extends self.ISpriteInstance {},
	EyebrowsGood: class extends self.ISpriteInstance {},
	SpeechBubble: class extends self.ISpriteInstance {},
	Hint: class extends self.IWorldInstance {},
	Pencil: class extends self.ISpriteInstance {},
	HintPathLine: class extends self.ISpriteInstance {},
	HintCursor: class extends self.ISpriteInstance {},
	EggExplosionSprite: class extends self.ISpriteInstance {},
	EggSilhouette: class extends self.ISpriteInstance {},
	P1_Image: class extends self.ISpriteInstance {},
	P2_Image: class extends self.ISpriteInstance {},
	Particles1: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Confetti: class extends self.ISpriteInstance {},
	ConfettiParticles: class extends self.IParticlesInstance {},
	Swing1: class extends self.IWorldInstance {},
	Swing2: class extends self.ISpriteInstance {},
	SwingPoint: class extends self.ISpriteInstance {},
	Rope: class extends self.ISpriteInstance {},
	RopeBase: class extends self.ISpriteInstance {},
	Stick: class extends self.ISpriteInstance {},
	Wheel: class extends self.ISpriteInstance {},
	LoadingText: class extends self.ISpriteFontInstance {},
	Logo: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	NoButton: class extends self.ISpriteInstance {},
	YesButton: class extends self.ISpriteInstance {},
	TutReset: class extends self.ISpriteInstance {},
	Gear: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	Family1: class extends self.ISpriteInstance {},
	LevelResetButtons: class extends self.ISpriteInstance {}
}