const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Plugins.GM_SDK,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LocalStorage.Cnds.CompareKey,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.GM_SDK.Cnds.ResumeGame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.SetMasterVolume
	];
};
self.C3_JsPropNameTable = [
	{BG_GAME: 0},
	{ballsCount: 0},
	{Done: 0},
	{celebrate: 0},
	{glass: 0},
	{index: 0},
	{Parent: 0},
	{ball: 0},
	{Touch: 0},
	{info_LevelGame: 0},
	{Sine: 0},
	{TITLE: 0},
	{TITLE2: 0},
	{PLAY_BTN: 0},
	{info: 0},
	{G: 0},
	{black: 0},
	{Level_Game: 0},
	{debug_info: 0},
	{c: 0},
	{Rotate: 0},
	{LABEL_LEVEL_COMPLETE: 0},
	{BTN_PLAYY: 0},
	{BTN_RETRY: 0},
	{one: 0},
	{LocalStorage: 0},
	{finish_level: 0},
	{MENU_GAME2: 0},
	{SOUND_OFF: 0},
	{BTN_TRASH: 0},
	{black2: 0},
	{CLEAR_LEVEL: 0},
	{NO_BTN: 0},
	{YES_BTN: 0},
	{Audio: 0},
	{home: 0},
	{refresh: 0},
	{Fade: 0},
	{Fade2: 0},
	{NG_STUDIO: 0},
	{GameMonetizeSDK: 0},
	{Tween: 0},
	{F_ball: 0},
	{F_glass: 0},
	{MENU_GAME: 0},
	{BTN_TWEEN: 0},
	{CLEAR_LS: 0},
	{selectedGlass: 0},
	{selectedBallFrame: 0},
	{glass_complete: 0},
	{qntdBalls: 0},
	{currentLevel: 0},
	{glassTarget: 0},
	{CorrectCount: 0},
	{sound: 0}
];

self.InstanceType = {
	BG_GAME: class extends self.ISpriteInstance {},
	glass: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	info_LevelGame: class extends self.ITextInstance {},
	TITLE: class extends self.ISpriteInstance {},
	TITLE2: class extends self.ISpriteInstance {},
	PLAY_BTN: class extends self.ISpriteInstance {},
	G: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	Level_Game: class extends self.ITextInstance {},
	debug_info: class extends self.ITextInstance {},
	c: class extends self.ISpriteInstance {},
	celebrate: class extends self.IParticlesInstance {},
	LABEL_LEVEL_COMPLETE: class extends self.ISpriteInstance {},
	BTN_PLAYY: class extends self.ISpriteInstance {},
	BTN_RETRY: class extends self.ISpriteInstance {},
	one: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	finish_level: class extends self.ITextInstance {},
	MENU_GAME2: class extends self.ISpriteInstance {},
	SOUND_OFF: class extends self.ISpriteInstance {},
	BTN_TRASH: class extends self.ISpriteInstance {},
	black2: class extends self.ISpriteInstance {},
	CLEAR_LEVEL: class extends self.ISpriteInstance {},
	NO_BTN: class extends self.ISpriteInstance {},
	YES_BTN: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	home: class extends self.ISpriteInstance {},
	refresh: class extends self.ISpriteInstance {},
	NG_STUDIO: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends self.IInstance {},
	F_ball: class extends self.ISpriteInstance {},
	F_glass: class extends self.ISpriteInstance {},
	MENU_GAME: class extends self.ISpriteInstance {},
	BTN_TWEEN: class extends self.ISpriteInstance {},
	CLEAR_LS: class extends self.ISpriteInstance {}
}